import test from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {buildDirectory,matchingContacts,phoneKey} from '../base44/shared/contactMatching.js';
import {createContactsDirectoryHandler,validateDirectory,canonicalJson} from '../base44/shared/contactsDirectory.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const person=(key,company)=>({key:key.repeat(64),row:2,name:'Test Person',builder:company.split(' - ')[0],company,phone:'(801) 555-0100',phone_key:'+18015550100',email:'person@example.com',email_key:'person@example.com',note:'',review_note:''});
const data={version:1,source:{filename:'test.xlsm',workbook_sha256:'d'.repeat(64),captured_at:'2026-09-12T16:52:34Z',location:'Approved Excel copy'},contacts:[person('a','Builder Home - PM'),person('b','Builder Home - River Bend 12')],job_references:[{row:2,builder:'Builder Home',subdivision:'River Bend',lot:'12',po:'700',oe:'800'}]};
const job={id:'job1',canonical_name:'Builder Home - 12 River Bend',builder:'Builder Home',po_numbers:['700'],oe_numbers:['800-01'],aliases:[]};
test('keeps builder contacts separate from specific assignments; order suffix resolves subdivision',()=>{const d=buildDirectory(data,[job]);assert.equal(d.contacts[0].job_ids.length,0);assert.deepEqual(d.contacts[1].auto_job_ids,['job1']);assert.equal(d.jobs[0].groups[0].subdivision,'River Bend');assert.deepEqual(d.jobs[0].groups[0].source_rows,[2]);});
test('ambiguous jobs require selection and saved links survive a new directory projection',()=>{const jobs=[job,{...job,id:'job2'}];const d=buildDirectory(data,jobs,[{contact_key:'b'.repeat(64),job_id:'job2'}]);assert.equal(d.contacts[1].candidate_count,2);assert.equal(d.contacts[1].auto_job_ids.length,0);assert.deepEqual(d.contacts[1].job_ids,['job2']);});
test('never combines a subdivision from one source row with a lot from another',()=>{const d=structuredClone(data);d.job_references=[{...d.job_references[0],subdivision:'River Bend',lot:'9'},{...d.job_references[0],row:3,subdivision:'Other Place',lot:'12'}];const result=buildDirectory(d,[{...job,canonical_name:'Builder Home multi-job order'}]);assert.equal(result.contacts[1].auto_job_ids.length,0);});
test('phone and email identity match exactly without matching name fragments',()=>{assert.equal(phoneKey('801-555-0100'),'+18015550100');assert.equal(matchingContacts(data.contacts,['+1 (801) 555-0100']).length,2);assert.equal(matchingContacts(data.contacts,['PERSON@example.com']).length,2);assert.equal(matchingContacts(data.contacts,['Test Person']).length,0);assert.equal(matchingContacts(data.contacts,['8015550101']).length,0);});
test('invalid and duplicate source rows fail validation',()=>{assert.equal(validateDirectory(data),data);assert.throws(()=>validateDirectory({...data,contacts:[data.contacts[0],data.contacts[0]]}));assert.throws(()=>validateDirectory({...data,source:{...data.source,workbook_sha256:'bad'}}));});
async function setup(){const tables={ContactDirectorySnapshot:[],HubContacts:[],ContactJobLink:[],Jobs:[job],MessageConversation:[]},api={};let user={role:'admin',email:'gabefronk@gmail.com'};let storedFile='';for(const [name,rows]of Object.entries(tables)){api[name]={list:async(sort,limit=500,skip=0)=>[...rows].reverse().slice(skip,skip+limit),filter:async(q,sort,limit=500)=>rows.filter(r=>Object.entries(q).every(([k,v])=>r[k]===v)).slice(0,limit),get:async id=>rows.find(r=>r.id===id),create:async r=>{const row={...structuredClone(r),id:name+rows.length};rows.push(row);return row},delete:async id=>{const i=rows.findIndex(r=>r.id===id);if(i>=0)rows.splice(i,1)}};}
 const integrations={Core:{UploadPrivateFile:async({file})=>{storedFile=await file.text();return {file_uri:'private://directory'}},CreateFileSignedUrl:async()=>({signed_url:'https://example.invalid/private-directory'})}};
 const handler=createContactsDirectoryHandler({getClient:async()=>({auth:{me:async()=>user},asServiceRole:{entities:api,integrations}}),fetchFile:async()=>new Response(storedFile)});
 return {tables,setUser:u=>user=u,call:async body=>handler(new Request('https://example.invalid',{method:'POST',body:JSON.stringify(body)}))};}
test('owner authorization precedes all data reads and imports',async()=>{const s=await setup();for(const user of [null,{role:'admin',email:'someone@example.com'},{role:'user',email:'gabefronk@gmail.com'}]){s.setUser(user);assert.equal((await s.call({action:'import',directory:data})).status,user?403:401);}assert.equal(s.tables.ContactDirectorySnapshot.length,0);});
test('import is idempotent and returns no private file URI; links can be saved and removed',async()=>{const s=await setup();const first=await s.call({action:'import',directory:data});assert.equal(first.status,200);assert.equal((await first.text()).includes('private://'),false);assert.equal((await(await s.call({action:'import',directory:data})).json()).duplicate,true);assert.equal(s.tables.ContactDirectorySnapshot.length,1);for(let n=0;n<2;n++)assert.equal((await s.call({action:'link',contact_key:'a'.repeat(64),job_id:'job1'})).status,200);assert.equal(s.tables.ContactJobLink.length,1);const directory=await(await s.call({action:'directory'})).json();assert.deepEqual(directory.contacts[0].manual_job_ids,['job1']);assert.equal(JSON.stringify(directory).includes('private://'),false);assert.equal((await s.call({action:'link',contact_key:'a'.repeat(64),job_id:'missing'})).status,400);await s.call({action:'link',contact_key:'a'.repeat(64),job_id:'job1',remove:true});assert.equal(s.tables.ContactJobLink.length,0);});

test('workbook jobs remain available when no Glass Forge job exists',()=>{const result=buildDirectory(data,[]);assert.equal(result.jobs.length,1);assert.equal(result.jobs[0].is_workbook,true);assert.deepEqual(result.jobs[0].oe_numbers,['800']);assert.equal(result.contacts[1].auto_job_ids[0],result.jobs[0].id);const saved=buildDirectory(data,[],[{contact_key:'a'.repeat(64),job_id:result.jobs[0].id}]);assert.equal(saved.contacts[0].manual_job_ids[0],result.jobs[0].id);});

test('connector snapshots stay private and verify their canonical checksum',async()=>{const s=await setup();const content=canonicalJson(data);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(content));const checksum=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');s.tables.ContactDirectorySnapshot.push({id:'connector',directory_data:structuredClone(data),content_sha256:checksum});const r=await s.call({action:'directory'});assert.equal(r.status,200);assert.equal((await r.json()).contacts.length,2);const bad=await setup();bad.tables.ContactDirectorySnapshot.push({id:'tampered',directory_data:structuredClone(data),content_sha256:'0'.repeat(64)});assert.equal((await bad.call({action:'directory'})).status,500);});

test('owner creates a current contact without a workbook, then explicitly links it to a job',async()=>{
 const s=await setup();const denied=await s.call({action:'create_contact',contact:{name:'Justin Hutchins',email:'justin@example.com'}});assert.equal(denied.status,201);
 const created=(await denied.json()).contact;assert.equal(created.name,'Justin Hutchins');assert.equal(s.tables.HubContacts.length,1);
 assert.equal((await s.call({action:'create_contact',contact:{name:'Duplicate',email:'justin@example.com'}})).status,409);
 assert.equal((await s.call({action:'link',contact_key:created.key,job_id:'job1',role:'homeowner'})).status,200);
 const d=await(await s.call({action:'directory'})).json();assert.equal(d.contacts.find(c=>c.key===created.key).manual_job_ids[0],'job1');
 s.setUser({role:'user',email:'crew@example.com'});assert.equal((await s.call({action:'create_contact',contact:{name:'Crew'}})).status,403);
});
