import test from 'node:test';
import assert from 'node:assert/strict';
import {createFieldLibraryHandler,sourceKey,hash,boundedBytes} from '../base44/shared/fieldLibrary.js';
function entity(){
 let rows=[],next=0;
 const matches=(row,q)=>Object.entries(q).every(([k,v])=>v&&typeof v==='object'?'$in' in v?v.$in.includes(row[k]):'$ne' in v?row[k]!==v.$ne:true:row[k]===v);
 return {rows:()=>rows,filter:async(q={},sort,limit=500,offset=0)=>rows.filter(r=>matches(r,q)).slice(offset,offset+limit),list:async()=>rows.slice().reverse(),get:async id=>rows.find(r=>r.id===id),create:async row=>{const r={...row,id:'row_'+(++next)};rows.push(r);return r;},update:async(id,row)=>{const i=rows.findIndex(r=>r.id===id);if(i<0)throw Error('not found');rows[i]={...rows[i],...row};return rows[i];},bulkCreate:async function(values){return Promise.all(values.map(v=>this.create(v)));}};
}
function setup(){
 const api=Object.fromEntries(['FieldLibraryImport','FieldLibraryProject','FieldLibraryReport','FieldLibraryFile','ProbuildControlDevice','ProbuildProjectLink'].map(n=>[n,entity()]));
 const source={projects:{project1:{name:'Builder One Lot 1',createdAt:'2024-01-01T00:00:00Z',archivedAt:'2026-01-01T00:00:00Z',users:{someone:true}},removed:{name:'Removed project',deletedAt:'2025-01-01T00:00:00Z'}},posts:{project1:{post1:{createdAt:'2026-09-11T22:51:42Z',message:'Original notes\nSecond line',attachments:{photo1:{type:'photo',generation:'100',imageMetadata:{width:4,height:3}}}},oldpost:{createdAt:'2024-02-02T10:00:00Z',message:'Removed original note',deletedAt:'2025-01-01T00:00:00Z'}},removed:{}}};
 let user={role:'admin',email:'gabefronk@gmail.com'},allowSource=true,corrupt=false,tokenReads=0,sourceBytes=null,badRange=false;const files=new Map();
 const client={auth:{me:async()=>user},asServiceRole:{entities:api,integrations:{Core:{UploadPrivateFile:async({file})=>{const uri='private:'+files.size;files.set(uri,new Uint8Array(await file.arrayBuffer()));return {file_uri:uri};},CreateFileSignedUrl:async({file_uri})=>({signed_url:'https://owned.test/'+file_uri})}}}};
 const fetchImpl=async (url,options={})=>{
  if(url.startsWith('https://owned.test/'))return new Response(corrupt?new Uint8Array([9]):files.get(url.split('/').pop()));
  if(!allowSource)throw Error('ProBuild is disconnected');
  if(url.includes('firebasestorage')){
   if(!sourceBytes)return new Response(new Uint8Array([1,2,3,4]),{headers:{'Content-Type':'image/jpeg'}});
   const [,a,b]=/bytes=(\d+)-(\d+)/.exec(options.headers.Range),start=Number(a),end=Math.min(Number(b),sourceBytes.length-1);
   return new Response(sourceBytes.slice(start,end+1),{status:206,headers:{'Content-Type':'video/mp4','Content-Range':`bytes ${badRange?start+1:start}-${end}/${sourceBytes.length}`}});
  }
  const path=url.split('/teams/')[1].split('/').slice(1).join('/').split('.json?')[0];return Response.json(path==='projects'?source.projects:source.posts[path.split('/')[1]]);
 };
 const handler=createFieldLibraryHandler({getClient:()=>client,getToken:async()=>{tokenReads++;if(!allowSource)throw Error('disconnected');return 'token';},fetchImpl,now:()=>new Date('2026-09-12T20:00:00Z')});
 const call=async payload=>{const response=await handler(new Request('https://local.test',{method:'POST',body:JSON.stringify(payload)}));return {status:response.status,...await response.json()};};
 return {api,source,call,handler,files,setUser:u=>user=u,disconnect:()=>allowSource=false,corrupt:()=>corrupt=true,tokenReads:()=>tokenReads,setSourceBytes:b=>sourceBytes=b,badRange:()=>badRange=true};
}
async function importAll(s){const {run}=await s.call({action:'start_import'});for(const project_id of run.project_ids)assert.equal((await s.call({action:'import_project',run_id:run.id,project_id})).status,200);return run;}
test('requires owner access and rejects malformed device key',async()=>{const s=setup();s.setUser({role:'admin',email:'another@example.com'});assert.equal((await s.call({action:'status'})).status,403);const r=await s.handler(new Request('https://local.test',{method:'POST',headers:{'x-glass-forge-control-key':'bad'},body:'{}'}));assert.equal(r.status,401);});
test('imports archived and removed history verbatim; resuming does not duplicate',async()=>{const s=setup(),run=await importAll(s);assert.equal(s.api.FieldLibraryProject.rows().length,2);assert.equal(s.api.FieldLibraryReport.rows().length,2);assert.equal(s.api.FieldLibraryFile.rows().length,1);const r=s.api.FieldLibraryReport.rows().find(r=>r.source_post_id==='post1');assert.deepEqual(r.source_snapshot,s.source.posts.project1.post1);assert.equal(r.message,'Original notes\nSecond line');assert.equal(r.report_date,'2026-09-11');await s.call({action:'import_project',run_id:run.id,project_id:'project1'});assert.equal(s.api.FieldLibraryReport.rows().length,2);assert.equal(s.api.FieldLibraryFile.rows().length,1);assert.equal((await s.call({action:'start_import'})).run.id,run.id);});
test('audit stays incomplete until every original file is copied and verified',async()=>{const s=setup(),run=await importAll(s);let a=(await s.call({action:'audit_import',run_id:run.id})).run;assert.equal(a.source_complete,true);assert.equal(a.files_complete,false);const f=s.api.FieldLibraryFile.rows()[0];assert.equal((await s.call({action:'copy_file',file_id:f.id})).file.status,'verified');a=(await s.call({action:'audit_import',run_id:run.id})).run;assert.equal(a.files_complete,true);assert.equal(a.bytes_verified,4);assert.equal((await s.call({action:'copy_file',file_id:f.id})).already_verified,true);assert.equal(s.files.size,1);});
test('saved reports and files work with ProBuild completely unavailable',async()=>{const s=setup();await importAll(s);const f=s.api.FieldLibraryFile.rows()[0];await s.call({action:'copy_file',file_id:f.id});const before=s.tokenReads();s.disconnect();const p=await s.call({action:'projects'});assert.equal(p.projects.length,1);const detail=await s.call({action:'project',project_id:p.projects[0].id});assert.equal(detail.reports.length,1);const file=await s.call({action:'file',source_key:f.source_key});assert.equal(file.status,200);assert.match(file.url,/owned.test/);assert.equal(s.tokenReads(),before);assert.equal('file_uri' in file.file,false);});
test('fails verification on altered stored bytes and refuses to serve that file',async()=>{const s=setup();await importAll(s);s.corrupt();const f=s.api.FieldLibraryFile.rows()[0];assert.equal((await s.call({action:'copy_file',file_id:f.id})).status,502);assert.equal((await s.call({action:'file',source_key:f.source_key})).status,409);assert.equal(s.api.FieldLibraryFile.rows()[0].status,'error');});
test('changed generations get new copies while preserving the verified previous version',async()=>{const s=setup(),run=await importAll(s);const old=s.api.FieldLibraryFile.rows()[0];await s.call({action:'copy_file',file_id:old.id});s.source.posts.project1.post1.attachments.photo1.generation='101';await s.call({action:'import_project',run_id:run.id,project_id:'project1'});assert.equal(s.api.FieldLibraryFile.rows().length,2);assert.equal(s.api.FieldLibraryFile.rows().find(f=>f.id===old.id).status,'verified');assert.equal(s.api.FieldLibraryReport.rows()[0].attachments[0].generation,'101');});
test('missing report records fail completeness and source IDs cannot escape the team path',async()=>{const s=setup(),run=(await s.call({action:'start_import'})).run;assert.equal((await s.call({action:'import_project',run_id:run.id,project_id:'../elsewhere'})).status,400);assert.equal((await s.call({action:'audit_import',run_id:run.id})).run.source_complete,false);assert.notEqual(sourceKey('a','b'),sourceKey('ab'));assert.equal((await hash('test')).length,64);});
test('rejects oversized files before accepting bytes',async()=>{await assert.rejects(()=>boundedBytes(new Response(new Uint8Array([1]),{headers:{'Content-Length':'999'}}),8),/transfer limit/);});
test('large files resume from verified pieces and remain readable without ProBuild',async()=>{
 const s=setup(),bytes=new Uint8Array(6*1048576+17);bytes.fill(37);bytes[bytes.length-1]=123;s.setSourceBytes(bytes);
 const run=await importAll(s),f=s.api.FieldLibraryFile.rows()[0];
 const first=await s.call({action:'copy_file',file_id:f.id});assert.equal(first.partial,true);assert.equal(first.file.bytes_stored,6*1048576);assert.equal(first.file.status,'copying');assert.equal((await s.call({action:'file',source_key:f.source_key})).status,409);
 const second=await s.call({action:'copy_file',file_id:f.id});assert.equal(second.partial,false);assert.equal(second.file.status,'verified');assert.equal(second.file.size,bytes.length);assert.equal(second.file.chunks.length,2);assert.equal(second.file.sha256,'');assert.equal(second.file.manifest_sha256.length,64);assert.equal('file_uri' in second.file.chunks[0],false);
 s.disconnect();const served=await s.call({action:'file',source_key:f.source_key});assert.equal(served.url,null);assert.equal(served.chunks.length,2);assert.deepEqual(served.chunks.map(p=>p.offset),[0,6*1048576]);assert.deepEqual(new Uint8Array(await new Blob([...s.files.values()]).arrayBuffer()),bytes);
 const audit=(await s.call({action:'audit_import',run_id:run.id})).run;assert.equal(audit.files_complete,true);assert.equal(audit.bytes_verified,bytes.length);
});
test('invalid source ranges never become saved file pieces',async()=>{
 const s=setup();s.setSourceBytes(new Uint8Array(6*1048576+1));s.badRange();await importAll(s);const f=s.api.FieldLibraryFile.rows()[0];
 const result=await s.call({action:'copy_file',file_id:f.id});assert.equal(result.status,502);assert.match(result.error,/invalid file range/);assert.equal(s.files.size,0);assert.equal(s.api.FieldLibraryFile.rows()[0].status,'error');
});
