import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {serviceRisk,latestIncomingTurn,checkDayBeforeAppointment,CUSTOMER_SERVICE_RULES} from '../base44/shared/messageSafety.mjs';
import {buildReplyRequest,validateReplyPlan} from '../base44/shared/replyPlanner.mjs';
import {createMessageAssistantHandler,validateAnalysis,SERVICE_ROUTE} from '../base44/shared/messageAssistant.js';
import {MESSAGE_DRAFT_POLICY_VERSION} from '../base44/shared/messageDraftPolicy.mjs';
import {triageEscalation,summarizeDecisionTriage} from '../base44/shared/decisionTriage.mjs';
const now='2026-09-14T18:00:00.000Z';
const conversation={conversation_key:'synthetic-thread',source_chat_guid:'synthetic-chat',participants:['+13035550123'],device_id:'synthetic-device',job_id:'synthetic-job',last_message_at:'2026-09-14T17:59:00.000Z'};
const job={id:'synthetic-job',name:'Sample Community Lot 42',builder:'Sample',builder_key:'sample',groups:[{lot:'42'}]};
const message=(text='Lot 42 patio door sticks.',extra={})=>({source_guid:'request',conversation_key:conversation.conversation_key,direction:'incoming',text,sent_at:conversation.last_message_at,attachments:[],...extra});
const model={is_service_request:true,source_request_guid:'request',summary:'Patio door sticks.',customer_name:'Synthetic',job_id:job.id,job_reason:'Exact lot.',issues:['Patio door sticks.'],source_message_guids:['request'],photo_guids:[],acknowledgment_already_sent:false,ack_evidence_guid:'',missing_info:[],service_text:'Please review the patio door at Lot 42.',reply_text:'Thanks for letting me know.'};
function build(text,goal='Acknowledge the report.',extra={}) { return buildReplyRequest({conversation,messages:[message(text)],policy:{...conversation,goal,approved_facts:[],style_examples:[]},now,observed_at:now,...extra}); }
for(const text of ['What does this cost?','Please refund $250.','Can we get a discount?','Is this covered under warranty?','The warranty was denied.','I am frustrated.','This is unacceptable.','Nobody showed up.']) test('risk preflight holds: '+text,()=>{ const b=build(text);assert.equal(b.request,null);assert.equal(b.preflight_plan.decision,'owner_needed');assert.equal(b.preflight_plan.reply_text,'');assert.match(b.preflight_plan.owner_note,/Gabe/);assert.equal(b.preflight_plan.send_enabled,false); });
test('ordinary service acknowledgment remains eligible for a draft',()=>{assert.ok(build('The patio door sticks.').request);assert.equal(serviceRisk('Are you free Tuesday?').owner_review_required,false);});
test('an earlier risky incoming message in the current turn is not hidden by a short follow-up',()=>{const b=build('Any update?',undefined,{messages:[message('I want a refund.',{source_guid:'first',sent_at:'2026-09-14T17:58:00.000Z'}),message('Any update?')]});assert.equal(b.preflight_plan.decision,'owner_needed');});
test('old unrelated financial history is not copied into a new routine turn',()=>{const list=[message('Invoice paid.',{source_guid:'old',sent_at:'2026-09-10T17:00:00Z'}),message('Thanks.',{source_guid:'old-out',direction:'outgoing',sent_at:'2026-09-10T17:01:00Z'}),message()];assert.equal(latestIncomingTurn(list).length,1);assert.ok(build(undefined,undefined,{messages:list}).request);});
test('Gabe takeover and duplicate acknowledgment remain controlling',()=>{const b=build(undefined,undefined,{messages:[message(),message('I will review this.',{source_guid:'out',direction:'outgoing',sent_at:now})]});assert.equal(b.preflight_plan.decision,'wait');});
test('model cannot introduce a money or warranty answer into a safe preview',()=>{const b=build();for(const reply_text of ['We will refund $200.','That is covered by warranty.']){const p=validateReplyPlan({decision:'reply',intent:'answer_from_context',reply_text,source_message_guids:['request'],owner_note:''},b.context);assert.equal(p.decision,'owner_needed');assert.equal(p.reply_text,'');assert.equal(p.send_enabled,false);}});
test('model-only subtle escalation flag clears both service draft texts',()=>{const r=validateAnalysis({...model,owner_review_required:true,owner_review_reason:'Customer relationship concern.'},{messages:[message()],jobs:[job],historyComplete:true});assert.equal(r.escalate_to,'Gabe');assert.equal(r.reply_text,'');assert.equal(r.service_text,'');});
test('wrong lot clears customer reply as well as service handoff',()=>{const r=validateAnalysis(model,{messages:[message('Lot 43 patio door sticks.')],jobs:[job],historyComplete:true});assert.equal(r.job,null);assert.equal(r.reply_text,'');assert.equal(r.service_text,'');});
test('invalid source GUID cannot retain dispatch or customer text',()=>{const r=validateAnalysis({...model,source_request_guid:'invented'},{messages:[message()],jobs:[job],historyComplete:true});assert.equal(r.reply_text,'');assert.equal(r.service_text,'');});
function fixture({text,mutation,modelResult=model}={}) {
 const calls={model:0,writes:0},state={convo:structuredClone(conversation),messages:[message(text)],capture:{history_complete:true}},stored=[];
 const api={MessageConversation:{filter:async()=>[structuredClone(state.convo)]},MessageRecord:{filter:async()=>structuredClone(state.messages)},MessageAssistantCapture:{filter:async()=>[structuredClone(state.capture)]},MessageServiceCase:{filter:async query=>stored.filter(row=>Object.entries(query).every(([k,v])=>row[k]===v)),create:async row=>{calls.writes++;const saved={...row,id:'saved-'+stored.length};stored.push(saved);return saved;},update:async(id,row)=>{calls.writes++;const index=stored.findIndex(r=>r.id===id);stored[index]={...row,id};return stored[index];}}};
 const client={auth:{me:async()=>({role:'admin',email:'gabefronk@gmail.com'})},asServiceRole:{entities:api,integrations:{Core:{InvokeLLM:async()=>{calls.model++;mutation?.(state);return structuredClone(modelResult);}}}}};
 const directory={source:'synthetic',contacts:[{name:'Synthetic',phone_key:conversation.participants[0],builder:'Sample',builder_key:'sample',job_ids:[job.id]}],jobs:[structuredClone(job)]};
 const handler=createMessageAssistantHandler({getClient:async()=>client,loadDirectory:async()=>structuredClone(directory),now:()=>new Date(now)});
 return {calls,state,stored,directory,run:()=>handler(new Request('https://example.invalid',{method:'POST',body:JSON.stringify({action:'analyze',conversation_key:conversation.conversation_key})}))};
}
test('sensitive service request bypasses model and has no service recipients',async()=>{const f=fixture({text:'Lot 42. I want a refund.'});const response=await f.run();assert.equal(response.status,200);const b=await response.json();assert.equal(f.calls.model,0);assert.equal(b.case.result.escalate_to,'Gabe');assert.equal(b.case.result.reply_text,'');assert.equal(b.case.result.service_text,'');assert.deepEqual(b.case.recipients,[]);assert.equal(b.case.destination_chat_guid,'');assert.equal(b.case.status,'needs_context');assert.equal((await (await f.run()).json()).cached,true);assert.equal(f.calls.writes,1);});
test('ordinary service path preserves approved route and cache',async()=>{const f=fixture();const b=await (await f.run()).json();assert.deepEqual(b.case.recipients,SERVICE_ROUTE.recipients);assert.equal(b.case.result.drafting_policy_version,MESSAGE_DRAFT_POLICY_VERSION);assert.equal((await (await f.run()).json()).cached,true);assert.equal(f.calls.model,1);});
for(const [label,change] of [['job link',s=>{s.convo.job_id='another-job';}],['participants',s=>{s.convo.participants.push('+13035550456');}],['message',s=>{s.messages[0].text='Changed request.';}],['history',s=>{s.capture.history_complete=false;}]]) test('service review rejects concurrent '+label+' change',async()=>{const f=fixture({mutation:change});assert.equal((await f.run()).status,409);assert.equal(f.calls.writes,0);});
test('directory evidence change invalidates cached service draft',async()=>{const f=fixture();await f.run();f.directory.jobs[0].address='New verified source address';await f.run();assert.equal(f.calls.model,2);});
test('capture completeness change invalidates cached service draft',async()=>{const f=fixture();await f.run();f.state.capture.history_complete=false;const b=await (await f.run()).json();assert.equal(f.calls.model,2);assert.equal(b.case.history_complete,false);});
const appointment={job_id:job.id,recipient:conversation.participants[0],status:'confirmed',cancelled:false,source_key:'synthetic-event',time_zone:'America/Denver',starts_at:'2026-09-15T16:00:00Z',checked_at:now};
test('day-before checks require exact confirmed fresh appointment evidence',()=>{const args={appointment,jobId:job.id,recipient:conversation.participants[0],now};assert.equal(checkDayBeforeAppointment(args).eligible,true);for(const change of [{status:'tentative'},{cancelled:true},{job_id:'other'},{recipient:'+13035550456'},{time_zone:'UTC'},{checked_at:'2026-09-13T18:00:00Z'},{starts_at:'2026-09-16T16:00:00Z'}])assert.equal(checkDayBeforeAppointment({...args,appointment:{...appointment,...change}}).eligible,false);});
for(const [label,current,start] of [['spring','2026-03-07T19:00:00Z','2026-03-08T16:00:00Z'],['fall','2026-10-31T18:00:00Z','2026-11-01T17:00:00Z']])test('day-before uses local calendar date across '+label+' daylight-saving change',()=>{assert.equal(checkDayBeforeAppointment({appointment:{...appointment,starts_at:start,checked_at:current},jobId:job.id,recipient:conversation.participants[0],now:current}).eligible,true);});
test('current reply endpoint cannot fabricate structured appointment or photo evidence',()=>{for(const goal of ['Prepare a day-before appointment confirmation.','Send a photo update.']){const b=build(undefined,goal);assert.equal(b.request,null);assert.equal(b.preflight_plan.decision,'owner_needed');}});
test('Microsoft route and no-send customer rules are explicit',()=>{assert.ok(CUSTOMER_SERVICE_RULES.includes('Never invent warranty coverage.'));assert.ok(CUSTOMER_SERVICE_RULES.some(r=>r.includes('iPad > MacBook')&&r.includes('No direct connectors')));});
test('triage offers read-only investigation, not final approval',()=>{const row={id:'sample',status:'needs_owner_decision',title:'Job data: calendar coverage gap',context:'Missing current capture.'};const before=JSON.stringify(row),t=triageEscalation(row);assert.equal(t.bucket,'bulk_safe_read_only_review');assert.equal(t.approval_granted,false);assert.equal(t.status_change_allowed,false);assert.equal(JSON.stringify(row),before);assert.equal(summarizeDecisionTriage([row]).safe_final_approvals,0);});
test('mixed, financial, identity and extraction exceptions fail closed',()=>{for(const row of [{title:'Job data: conflicting fee identity'},{title:'Job data: no exact identity'},{title:'Job data: pdf extraction needs review'},{title:'Unknown action'},{title:'Job data: calendar coverage gap',context:'Refund and warranty dispute.'}])assert.equal(triageEscalation(row).bucket,'gabe_decision');});
test('only report-only daily snapshots are batch-safe',()=>{const row={agent_id:'calendar_ops_lead',title:'Daily run exception: Calendar Operations Lead',context:'Reconciled 179 scheduled events: 15 pending, 8 missing/incomplete reports, 8 past grace.'};assert.equal(triageEscalation(row).bucket,'bulk_safe_read_only_review');assert.equal(triageEscalation({...row,context:row.context+' Job preparation: conflicting fee identity.'}).bucket,'gabe_decision');});
test('UI explicitly holds legacy drafts and backend-policy mismatch',()=>{const src=fs.readFileSync(new URL('../src/components/messages/MessageAssistantPanel.jsx',import.meta.url),'utf8');assert.match(src,/!backendCurrent\|\|/);assert.match(src,/!draftHeld&&result\.service_text/);assert.match(src,/!draftHeld&&result\.reply_text/);assert.match(src,/serviceRevision\.current!==revision/);});

test('timezone-free appointment timestamps cannot pass day-before validation',()=>{assert.equal(checkDayBeforeAppointment({appointment:{...appointment,starts_at:'2026-09-15T16:00:00'},jobId:job.id,recipient:conversation.participants[0],now}).eligible,false);});
test('new sensitive review preserves completed history in a separate hold',async()=>{const f=fixture();await f.run();f.stored[0].status='completed';const original=structuredClone(f.stored[0]);f.state.messages[0].text='Lot 42. I want a refund.';const b=await (await f.run()).json();assert.equal(f.stored.length,2);assert.deepEqual(f.stored[0],original);assert.equal(b.case.status,'needs_context');assert.equal(b.case.result.escalate_to,'Gabe');assert.deepEqual(b.case.recipients,[]);await f.run();assert.equal(f.stored.length,2);});
