import test from 'node:test';
import assert from 'node:assert/strict';
import {validateAnalysis,createMessageAssistantHandler,SERVICE_ROUTE} from '../base44/shared/messageAssistant.js';
const messages=[{source_guid:'request',direction:'incoming',text:'SC14 door trim popping off; basement door not opening.',sent_at:'2026-09-11T18:00:00Z',attachments:[]},{source_guid:'photos',direction:'incoming',sent_at:'2026-09-11T18:01:00Z',attachments:[{guid:'p1',status:'ready',file_uri:'secret'}]},{source_guid:'ack',direction:'outgoing',sent_at:'2026-09-11T18:02:00Z',text:'I will get this sent in.'}];
const result={is_service_request:true,source_request_guid:'request',job_id:'j1',issues:['Trim loose','Basement door not opening'],source_message_guids:['request','photos'],photo_guids:['p1'],acknowledgment_already_sent:true,ack_evidence_guid:'ack',reply_text:'Absolutely',service_text:'Please coordinate service',missing_info:[]};
test('existing acknowledgment suppresses duplicate reply; original photos stay private',()=>{const r=validateAnalysis(result,{messages,jobs:[{id:'j1',name:'Summit Creek 14',groups:[{lot:'14'}]}],historyComplete:true});assert.equal(r.reply_text,'');assert.equal(r.acknowledgment_already_sent,true);assert.equal(r.photos[0].file_uri,undefined);assert.equal(r.issues.length,2);assert.equal(r.missing_info.length,0)});
test('unmatched job, unverified acknowledgment and fabricated photo cannot pass',()=>{const r=validateAnalysis({...result,job_id:'other',ack_evidence_guid:'request',photo_guids:['fabricated']},{messages,jobs:[{id:'j1'}],historyComplete:false});assert.equal(r.job,null);assert.equal(r.acknowledgment_already_sent,false);assert.ok(r.missing_info.length>=4);assert.deepEqual(r.photos,[])});
test('registered service route excludes customer groups',()=>{assert.deepEqual(SERVICE_ROUTE.recipients,['+13855054784','+13853955930']);assert.equal(SERVICE_ROUTE.chat_guid,'iMessage;+;chat122175084419934254')});
test('unauthorized users rejected before data or LLM lookup',async()=>{let touched=false;for(const user of [null,{role:'user',email:'gabefronk@gmail.com'},{role:'admin',email:'someone@example.com'}]){const h=createMessageAssistantHandler({getClient:async()=>({auth:{me:async()=>user},asServiceRole:{entities:{}}}),loadDirectory:async()=>{touched=true}});const r=await h(new Request('https://test',{method:'POST',body:JSON.stringify({action:'analyze'})}));assert.equal(r.status,403);assert.match(r.headers.get('Cache-Control'),/no-store/)}assert.equal(touched,false)});

test('explicit SC14 cannot match an old lot 69 in the same customer thread',()=>{const r=validateAnalysis(result,{messages,jobs:[{id:'j1',name:'Ridge View 69',groups:[{lot:'69'}]}],historyComplete:true});assert.equal(r.job,null);assert.equal(r.service_text,'');assert.ok(r.missing_info.some(x=>x.includes('conflicts')))});
