import test from 'node:test';
import assert from 'node:assert/strict';
import { buildAgentInventory, createAgentCenterHandler, isAgentCenterOwner } from '../shared/agentCenter.js';
import { isAgentCenterOwner as uiOwner } from '../../src/lib/agentCenterAccess.js';
const now=new Date('2026-09-10T12:00:00Z');
function harness(user={email:'gabefronk@gmail.com',role:'admin'}){
 const entries=[],escalations=[],events=[],connections=[];let n=0;
 const list=rows=>async()=>rows;
 const byKey=rows=>async q=>rows.filter(r=>Object.entries(q).every(([k,v])=>r[k]===v));
 const create=rows=>async row=>{const r={...row,id:'row-'+(++n)};rows.push(r);return r};
 const update=rows=>async(id,patch)=>{const row=rows.find(x=>x.id===id);Object.assign(row,patch);return row};
 const entities={SalesTrackerSnapshot:{filter:async()=>[]},AgentCenterEntry:{list:list(entries),filter:byKey(entries),create:create(entries)},AgentCenterEscalation:{list:list(escalations),filter:byKey(escalations),create:create(escalations),update:update(escalations)},AgentCenterEvent:{list:list(events),filter:byKey(events),create:create(events)},AgentCenterConnection:{list:list(connections),filter:byKey(connections),create:create(connections),update:update(connections)}};
 const handler=createAgentCenterHandler({getClient:async()=>({auth:{me:async()=>user},asServiceRole:{entities}}),now:()=>now});
 const call=async body=>{const r=await handler(new Request('https://test',{method:'POST',body:JSON.stringify(body)}));return {status:r.status,body:await r.json()}};
 return {call,entries,escalations,connections};
}
test('owner gate is identical in UI and server and accepts both verified Gabriel accounts only',()=>{for(const [user,yes] of [[null,false],[{email:'iryedra@gmail.com',role:'admin'},false],[{email:'trevor.draney7@gmail.com',role:'admin'},false],[{email:'gabefronk@gmail.com',role:'user'},false],[{email:'gabefronk@gmail.com',role:'admin'},true],[{email:'gabriel.fronk.wd@gmail.com',role:'admin'},true]]){assert.equal(isAgentCenterOwner(user),yes);assert.equal(uiOwner(user),yes)}});
test('tree includes a manager and planned external Claude integration',()=>{const nodes=buildAgentInventory({now});assert.equal(nodes.find(x=>x.id==='manager_agent').parent_id,null);assert.equal(nodes.find(x=>x.id==='external_claude_agents').connection,'planned');assert.equal(nodes.find(x=>x.id==='external_claude_agents').provider,'Anthropic Claude');});
test('a manager request creates a private owner escalation and does not dispatch',async()=>{const h=harness();const r=await h.call({action:'entry',target_id:'calendar_coordinator',kind:'request',title:'Clarify schedule',body:'Conflicting job dates.',request_key:'request-key-123456789'});assert.equal(r.status,200);assert.equal(r.body.delivery,'Not dispatched. Requests wait for the owner decision queue.');assert.equal(h.escalations.length,1);assert.equal(h.escalations[0].status,'needs_owner_decision');const resolved=await h.call({action:'resolve_escalation',escalation_id:h.escalations[0].id,resolution:'Keep the confirmed date.'});assert.equal(resolved.status,200);assert.equal(h.escalations[0].status,'answered');});
test('connection setup stores only a secret name and test remains planned without a real secret',async()=>{const h=harness();const prep=await h.call({action:'connection_prepare',provider_id:'anthropic_claude',scope_summary:'Status only',auth_method:'api_key'});assert.equal(prep.status,200);assert.equal(h.connections[0].connection_state,'planned');assert.equal(h.connections[0].secret_reference,'ANTHROPIC_API_KEY');assert.ok(!JSON.stringify(h.connections).match(/key_value|secret_value|password/i));const status=await h.call({action:'connection_status',provider_id:'anthropic_claude'});assert.equal(status.body.configured,false);assert.match(status.body.message,/ANTHROPIC_API_KEY/);const tested=await h.call({action:'connection_test',provider_id:'anthropic_claude'});assert.equal(tested.body.verified,false);assert.match(tested.body.message,/ANTHROPIC_API_KEY/);const off=await h.call({action:'connection_disconnect',provider_id:'anthropic_claude'});assert.equal(off.status,200);assert.equal(h.connections[0].connection_state,'disconnected');});
test('Trevor and Israel cannot use private inventory or connection actions',async()=>{for(const email of ['trevor@example.com','iryedra@gmail.com']){const h=harness({email,role:'admin'});for(const action of ['inventory','connection_prepare','connection_test'])assert.equal((await h.call({action,provider_id:'anthropic_claude',scope_summary:'x',auth_method:'api_key'})).status,403);}});
