import test from 'node:test';
import assert from 'node:assert/strict';
import {makeCalendarReview,validateCalendarReview,verifyCalendarReviews,importCalendarReview,calendarReviewContent,calendarReviewHash,calendarEventIdentity,calendarReviewEvidence,isCalendarReviewOwner} from '../shared/calendarReview.mjs';
const NOW='2026-09-13T20:00:00Z', HASH='a'.repeat(64), OWNER={role:'admin',email:'gabefronk@gmail.com'};
const job={id:'j1',canonical_name:'Acme Homes - 16 Pine Grove',aliases:[],po_numbers:['12345'],oe_numbers:['18123456']};
const event=()=>({calendar_name:'UT DC Service',source_occurrence_key:'local:one',event_date:'2026-09-14',job_name:job.canonical_name,address:'',scope_notes:'PO: 12345\nOE: 18123456-00\nInspect latch.',captured_at:'2026-09-13T19:10:00Z',source_start_date:'2026-09-14',source_end_date:'2026-09-14',multi_day:false,all_day:true,start_time:'',end_time:'',available_description_verified:true,source_date_labels_verified:true,screening:{capture_details:true,ownership_verified:false}});
const deferred=()=>({source_occurrence_key:'local:two',event_date:'2026-09-14',job_name:'Unknown job',screening:{capture_details:false,ownership_verified:false}});
async function fixture(patch={}) {
  const manifest={calendar_name:'UT DC Service',timezone:'America/Denver',range_start:'2026-09-14',range_end:'2026-09-15',agenda_scan_first_observed_at:'2026-09-13T19:00:00Z',agenda_scan_last_observed_at:'2026-09-13T19:30:00Z',complete:false,full_calendar_details_complete:false,agenda_coverage_complete:true,selected_detail_coverage_complete:true,missing_selected_details:0,tracker_source:{sha256:HASH,captured_at:'2026-09-12T07:03:00Z'},selected_detail_count:1,deferred_agenda_count:1,agenda_event_count:2};
  return makeCalendarReview({packageSha256:HASH,manifest,selectedEvents:[event()],deferredAgenda:[deferred()],dailyCoverage:{'2026-09-14':{agenda_complete:true,selected_details_complete:true,agenda_entry_count:2,selected_entry_count:1,selected_details_captured:1,deferred_title_count:1},'2026-09-15':{agenda_complete:true,selected_details_complete:true,agenda_entry_count:0,selected_entry_count:0,selected_details_captured:0,deferred_title_count:0}},...patch},NOW);
}
function db(rows=[]) { const data=structuredClone(rows),calls=[];return {data,calls,entities:{CalendarReviewCapture:{filter:async q=>data.filter(r=>r.capture_key===q.capture_key),create:async row=>{calls.push('create');const r={...structuredClone(row),id:'capture'+data.length};data.push(r);return r;}}}}; }
test('verified selected scope retains explicit empty days and false full completeness',async()=>{const r=await fixture();assert.equal((await verifyCalendarReviews([r],NOW)).captures.length,1);assert.equal(r.complete,false);assert.equal(r.daily_coverage['2026-09-15'].agenda_entry_count,0);});
test('full replacement or promoted ownership is rejected',async()=>{for(const field of ['complete','full_calendar_details_complete']){const r=await fixture();r[field]=true;assert.throws(()=>validateCalendarReview(r,NOW),/scope_flags/);}const r=await fixture();r.selected_events[0].screening.ownership_verified=true;assert.throws(()=>validateCalendarReview(r,NOW),/ownership/);});
test('selected and deferred sets cannot share occurrence identity',async()=>{const r=await fixture();r.deferred_agenda[0].source_occurrence_key='local:one';assert.throws(()=>validateCalendarReview(r,NOW),/occurrence_key/);});
test('missing zero day or changed per-day partition is incomplete',async()=>{let r=await fixture();delete r.daily_coverage['2026-09-15'];assert.throws(()=>validateCalendarReview(r,NOW),/daily_coverage/);r=await fixture();r.daily_coverage['2026-09-14'].deferred_title_count=0;assert.throws(()=>validateCalendarReview(r,NOW),/daily_partition/);});
test('source spans and exact clocks must be verified without inventing a time',async()=>{const r=await fixture();r.selected_events[0].source_end_date='2026-09-13';assert.throws(()=>validateCalendarReview(r,NOW),/source_dates/);const q=await fixture();q.selected_events[0].all_day=false;assert.throws(()=>validateCalendarReview(q,NOW),/clock/);});
test('impossible dates, wrong timezone and future observation reject',async()=>{for(const patch of [{range_end:'2026-02-30'},{timezone:'UTC'},{captured_at:'2030-01-01T00:00:00Z'}]){const r={...await fixture(),...patch};assert.throws(()=>validateCalendarReview(r,NOW));}});
test('note edits and duplicate captures fail integrity readback',async()=>{let r=await fixture();r.selected_events[0].scope_notes+=' Changed.';assert.equal((await verifyCalendarReviews([r],NOW)).rejected[0].reason,'capture_content_hash_mismatch');r=await fixture();assert.equal((await verifyCalendarReviews([r,{...r,id:'other'}],NOW)).captures.length,0);});
test('import requires exact owner and has no source/job/billing writer',async()=>{const api=db(),record=await fixture();await assert.rejects(()=>importCalendarReview({api,user:{role:'admin',email:'other@example.test'},record,now:NOW}),/owner/);assert.deepEqual(api.calls,[]);assert.equal(isCalendarReviewOwner(OWNER),true);});
test('retry imports one immutable record and preserves source notes byte for byte',async()=>{const api=db(),r=await fixture();await importCalendarReview({api,user:OWNER,record:r,now:NOW});const again=await importCalendarReview({api,user:OWNER,record:r,now:NOW});assert.equal(again.status,'already_imported');assert.equal(api.data.length,1);assert.equal(api.data[0].selected_events[0].scope_notes,event().scope_notes);});
test('changed existing content is never overwritten',async()=>{const r=await fixture(),api=db([{...r,id:'prior'}]),other=structuredClone(r);other.selected_events[0].scope_notes+=' edit';other.content_sha256=await calendarReviewHash(calendarReviewContent(other));await assert.rejects(()=>importCalendarReview({api,user:OWNER,record:other,now:NOW}),/existing_capture_differs/);assert.deepEqual(api.calls,[]);});
test('a create whose response was lost can be retried without duplicate writes',async()=>{const api=db(),r=await fixture(),original=api.entities.CalendarReviewCapture.create;api.entities.CalendarReviewCapture.create=async row=>{await original(row);throw Error('response lost');};await assert.rejects(()=>importCalendarReview({api,user:OWNER,record:r,now:NOW}),/response lost/);assert.equal((await importCalendarReview({api,user:OWNER,record:r,now:NOW})).status,'already_imported');assert.equal(api.data.length,1);});
test('known labeled order and exact complete identity tolerate a service prefix',()=>{const e={...event(),job_name:'MDS - #1 (LI) ACME 16 PINE GROVE'};assert.equal(calendarEventIdentity(e,[job]).job_id,'j1');});
test('unknown or contradictory supplied order cannot fall back to name',()=>{assert.equal(calendarEventIdentity({...event(),scope_notes:'PO: 99999'},[job]).reason,'supplied_order_unknown');const other={...job,id:'j2',canonical_name:'Acme - 17 Pine Grove',po_numbers:['99999']};assert.equal(calendarEventIdentity({...event(),scope_notes:'PO: 99999'},[job,other]).reason,'supplied_order_conflict');});
test('multi-unit ranges and duplicate exact catalog identities remain review',()=>{assert.equal(calendarEventIdentity({...event(),job_name:'Acme - 16-19 Pine Grove'},[job]).reason,'multiple_lots_or_units');assert.equal(calendarEventIdentity(event(),[job,{...job,id:'duplicate'}]).reason,'multiple_exact_jobs');});
test('failed identity never falls through into generic matching',async()=>{const r=await fixture();r.selected_events[0].scope_notes='PO: 99999';const out=calendarReviewEvidence({captures:[r],jobs:[job],now:NOW});assert.equal(out.evidence.length,0);assert.equal(out.diagnostics[0].reason,'supplied_order_unknown');});
test('selected source completeness remains false and deferred entries never become events',async()=>{const out=calendarReviewEvidence({captures:[await fixture()],jobs:[job],now:NOW});assert.equal(out.evidence.length,1);assert.equal(out.source_status.outlook_service_selected.complete,false);assert.match(out.evidence[0].status,/cancellation_unverified/);assert.equal(out.evidence[0].source_updated_at,null);});
test('local occurrence references from different captures do not collapse or cancel history',async()=>{const newer=await fixture(),older=await fixture({packageSha256:'b'.repeat(64)});older.captured_at='2026-09-13T19:20:00Z';older.source_manifest.agenda_scan_last_observed_at=older.captured_at;const out=calendarReviewEvidence({captures:[newer,older],jobs:[job],now:NOW});assert.equal(new Set(out.evidence.map(e=>e.source_id)).size,2);assert.equal(out.evidence.filter(e=>e.kind==='service_scheduled').length,1);assert.equal(out.evidence.filter(e=>e.kind==='note').length,1);assert.ok(out.evidence.every(e=>!['cancelled','deleted','superseded'].includes(e.status)));});

