// Generated by scripts/build-todos-entry.mjs from base44/shared/todoService.mjs
// (tested by tests/todoService.test.mjs). Edit that module and rebuild; do not edit by hand.
import { createClientFromRequest } from 'npm:@base44/sdk@0.8.48';

// Per-person to-do backend for the Glass Forge Hub.
// Every read and write is authorized here, server-side, with the service role.
// Crew members see only their own list. Gabriel (member_key "gabriel") is the
// only owner: team views, assignment to others, member management.

const PAGE_SIZE = 100;
const MAX_LIST_LIMIT = 500;
const MAX_USERS = 200;
const KEY_RE = /^[A-Za-z0-9:_-]+$/;
const STATUSES = new Set(["open", "in_progress", "done"]);
// Board lanes. "" is a valid stored value (tasks created before categories existed)
// and is shown in its own "Needs a category" lane so nothing is hidden.
const CATEGORIES = new Set(["", "quote_request", "odd_end", "order", "follow_up"]);
const BOARD_DONE_LIMIT = 50;
const OWNER_PATCH_FIELDS = new Set(["title", "details", "due_date", "assignee_member_id", "status", "progress_note", "category", "job_id"]);
const CREW_PATCH_FIELDS = new Set(["status", "progress_note", "category", "job_id"]);
const CREATE_FIELDS = new Set(["action", "title", "details", "assignee_member_id", "due_date", "request_key", "category", "job_id"]);

function fail(status, message) {
  throw Object.assign(new Error(message), { status });
}

function text(value, max, { required = false } = {}) {
  if (value === undefined || value === null) value = "";
  if (typeof value !== "string" || value.length > max || /[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(value)) fail(400, "Invalid text field.");
  if (required && !value.trim()) fail(400, "A required field is blank.");
  return value;
}

function idText(value, { required = false } = {}) {
  const v = text(value, 120, { required });
  if (v && !KEY_RE.test(v)) fail(400, "Invalid identifier.");
  return v;
}

function requestKey(value) {
  const v = text(value, 180, { required: true });
  if (!KEY_RE.test(v)) fail(400, "Invalid request key.");
  return v;
}

function dueDate(value) {
  const v = text(value, 10);
  if (v === "") return "";
  if (!/^\d{4}-\d{2}-\d{2}$/.test(v)) fail(400, "Invalid due date.");
  const d = new Date(v + "T00:00:00Z");
  if (Number.isNaN(d.getTime()) || d.toISOString().slice(0, 10) !== v) fail(400, "Invalid due date.");
  return v;
}

function statusValue(value) {
  const v = text(value, 20, { required: true });
  if (!STATUSES.has(v)) fail(400, "Invalid status.");
  return v;
}

function categoryValue(value) {
  const v = text(value, 40);
  if (!CATEGORIES.has(v)) fail(400, "Invalid category.");
  return v;
}

function offsetValue(value) {
  if (value === undefined || value === null || value === "") return 0;
  if (!Number.isInteger(value) || value < 0 || value > 100000) fail(400, "Invalid offset.");
  return value;
}

function publicMember(m) {
  return {
    id: m.id,
    member_key: m.member_key,
    display_name: m.display_name,
    active: m.active === true,
    pending_account: !Array.isArray(m.auth_user_ids) || m.auth_user_ids.length === 0,
    revision: m.revision ?? 0,
    seed_state: m.seed_state || "pending",
  };
}

function ownerMember(m) {
  return { ...publicMember(m), auth_user_ids: [...(m.auth_user_ids || [])] };
}

function countsOf(tasks) {
  const c = { open: 0, in_progress: 0, done: 0, total: 0 };
  for (const t of tasks) {
    if (STATUSES.has(t.status)) c[t.status] += 1;
    c.total += 1;
  }
  return c;
}

function slugify(name) {
  const s = String(name || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40);
  return s || "person";
}

function createTodoHandler({ getClient, isOwner, now = () => new Date().toISOString(), uuid = () => crypto.randomUUID() }) {
  if (typeof getClient !== "function" || typeof isOwner !== "function") fail(500, "Todo service is misconfigured.");

  const reply = (body, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { "content-type": "application/json", "Cache-Control": "no-store" },
    });

  // Which list the caller may see: their own, one person's (owner), or everyone's (owner).
  async function resolveView(api, caller, owner, input) {
    const view = input.member_id === undefined || input.member_id === "" ? "mine" : idText(input.member_id);
    const allMembers = await api.TeamMember.list("id", MAX_LIST_LIMIT, 0);
    let targetId = caller.id;
    if (view === "all") {
      if (!owner) fail(403, "Only Gabriel can view team tasks.");
      targetId = null;
    } else if (view !== "mine") {
      if (!owner) fail(403, "Only Gabriel can view other lists.");
      const target = allMembers.find((m) => m.id === view);
      if (!target) fail(404, "Person not found.");
      targetId = target.id;
    }
    const query = targetId === null ? { archived_at: "" } : { assignee_member_id: targetId, archived_at: "" };
    return { view, allMembers, query };
  }

  function teamSummary(allMembers, tasks) {
    return allMembers.map((m) => {
      const mine = tasks.filter((t) => t.assignee_member_id === m.id);
      const p = publicMember(m);
      return { id: p.id, member_key: p.member_key, display_name: p.display_name, active: p.active, pending_account: p.pending_account, counts: countsOf(mine) };
    });
  }

  async function listTasks(api, caller, owner, input) {
    const offset = offsetValue(input.offset);
    const { view, allMembers, query } = await resolveView(api, caller, owner, input);
    const tasks = await api.TodoTask.filter(query, "created_at", MAX_LIST_LIMIT, 0);
    const counts = countsOf(tasks);
    const page = tasks.slice(offset, offset + PAGE_SIZE);
    const body = {
      ok: true,
      owner,
      member: owner ? ownerMember(caller) : publicMember(caller),
      members: owner ? allMembers.map(ownerMember) : [publicMember(caller)],
      tasks: page,
      counts,
      has_more: offset + page.length < counts.total,
      offset,
    };
    if (view === "all") body.team_summary = teamSummary(allMembers, tasks);
    return body;
  }

  // Board view: every open and in-progress task (no paging, so nothing active is
  // pushed off the page by old completed tasks) plus the most recently finished ones.
  async function boardTasks(api, caller, owner, input) {
    const { view, allMembers, query } = await resolveView(api, caller, owner, input);
    const [open, inProgress, done] = await Promise.all([
      api.TodoTask.filter({ ...query, status: "open" }, "created_at", MAX_LIST_LIMIT, 0),
      api.TodoTask.filter({ ...query, status: "in_progress" }, "created_at", MAX_LIST_LIMIT, 0),
      api.TodoTask.filter({ ...query, status: "done" }, "-completed_at", BOARD_DONE_LIMIT, 0),
    ]);
    const active = [...open, ...inProgress];
    const body = {
      ok: true,
      owner,
      member: owner ? ownerMember(caller) : publicMember(caller),
      members: owner ? allMembers.map(ownerMember) : [publicMember(caller)],
      tasks: active,
      recent_done: done,
      counts: { open: open.length, in_progress: inProgress.length, recent_done: done.length },
      // Hitting a limit means the board may be incomplete; the UI says so.
      truncated: open.length >= MAX_LIST_LIMIT || inProgress.length >= MAX_LIST_LIMIT,
    };
    if (view === "all") body.team_summary = teamSummary(allMembers, active);
    return body;
  }

  async function getTask(api, caller, owner, input) {
    const id = idText(input.id, { required: true });
    let task;
    try {
      task = await api.TodoTask.get(id);
    } catch {
      fail(404, "Task not found.");
    }
    if (!owner && task.assignee_member_id !== caller.id) fail(404, "Task not found.");
    return { ok: true, task };
  }

  async function createTask(api, caller, owner, input, deps) {
    const key = requestKey(input.request_key);
    if (caller.management_lock) fail(409, "A previous write needs review before new tasks are added.");
    const unknown = Object.keys(input).filter((k) => !CREATE_FIELDS.has(k));
    if (unknown.length) fail(400, "Unexpected task fields.");
    const title = text(input.title, 200, { required: true });
    const details = text(input.details, 5000);
    const due_date = dueDate(input.due_date);
    const category = categoryValue(input.category);
    const job_id = idText(input.job_id);
    if (job_id) {
      try { await api.Jobs.get(job_id); } catch { fail(400, "Job not found."); }
    }
    const members = await api.TeamMember.list("id", MAX_LIST_LIMIT, 0);
    let assigneeId;
    const wanted = idText(input.assignee_member_id);
    if (wanted === "") {
      assigneeId = caller.id;
    } else if (owner) {
      const target = members.find((m) => m.id === wanted);
      if (!target) fail(404, "Person not found.");
      assigneeId = target.id;
    } else {
      if (wanted !== caller.id) fail(403, "Tasks can only be added to your own list.");
      assigneeId = caller.id;
    }
    const duplicates = await api.TodoTask.filter({ request_key: key }, "id", 2, 0);
    if (duplicates.length) {
      const existing = duplicates[0];
      const same = existing.title === title && (existing.details || "") === details && (existing.due_date || "") === due_date && existing.assignee_member_id === assigneeId && (existing.category || "") === category && (existing.job_id || "") === job_id;
      if (!same) fail(409, "This request key was already used for a different task.");
      return { ok: true, task: existing, duplicate: true };
    }
    const user = deps.user;
    const stamp = deps.now();
    const row = {
      title,
      details,
      assignee_member_id: assigneeId,
      status: "open",
      progress_note: "",
      due_date,
      category,
      job_id,
      created_by_user_id: user.id,
      assigned_by_user_id: user.id,
      completed_at: "",
      completed_by_user_id: "",
      archived_at: "",
      revision: 0,
      request_key: key,
      seed_key: "",
      created_at: stamp,
      updated_at: stamp,
    };
    let created;
    try {
      created = await api.TodoTask.create(row);
    } catch (e) {
      try {
        await api.TeamMember.updateMany({ id: caller.id }, { $set: { management_lock: "unreconciled-" + deps.uuid() } });
      } catch {}
      fail(500, "The task save result is uncertain and was locked for review.");
    }
    return { ok: true, task: created };
  }

  async function updateTask(api, caller, owner, input, deps) {
    const id = idText(input.id, { required: true });
    if (!Number.isInteger(input.expected_revision) || input.expected_revision < 0) fail(400, "A current revision is required.");
    const patch = input.patch;
    if (!patch || typeof patch !== "object" || Array.isArray(patch)) fail(400, "Invalid patch.");
    const keys = Object.keys(patch);
    if (!keys.length) fail(400, "Empty patch.");
    const allowed = owner ? OWNER_PATCH_FIELDS : CREW_PATCH_FIELDS;
    for (const k of keys) {
      if (!OWNER_PATCH_FIELDS.has(k)) fail(400, "Unknown task field.");
      if (!allowed.has(k)) fail(403, "Only Gabriel can change that field.");
    }
    let task;
    try {
      task = await api.TodoTask.get(id);
    } catch {
      fail(404, "Task not found.");
    }
    if (!owner && task.assignee_member_id !== caller.id) fail(404, "Task not found.");
    if (task.archived_at) fail(409, "Archived tasks cannot be edited.");
    if (task.revision !== input.expected_revision) fail(409, "This task changed; reload before saving.");
    const stamp = deps.now();
    const set = { updated_at: stamp };
    if ("title" in patch) set.title = text(patch.title, 200, { required: true });
    if ("details" in patch) set.details = text(patch.details, 5000);
    if ("due_date" in patch) set.due_date = dueDate(patch.due_date);
    if ("progress_note" in patch) set.progress_note = text(patch.progress_note, 3000);
    if ("category" in patch) set.category = categoryValue(patch.category);
    if ("job_id" in patch) {
      const jobId = idText(patch.job_id);
      if (jobId) {
        try { await api.Jobs.get(jobId); } catch { fail(400, "Job not found."); }
      }
      set.job_id = jobId;
    }
    if ("status" in patch) {
      const s = statusValue(patch.status);
      set.status = s;
      if (s === "done") {
        set.completed_at = stamp;
        set.completed_by_user_id = deps.user.id;
      } else {
        set.completed_at = "";
        set.completed_by_user_id = "";
      }
    }
    if ("assignee_member_id" in patch) {
      const wanted = idText(patch.assignee_member_id, { required: true });
      const members = await api.TeamMember.list("id", MAX_LIST_LIMIT, 0);
      const target = members.find((m) => m.id === wanted);
      if (!target) fail(404, "Person not found.");
      set.assignee_member_id = target.id;
      set.assigned_by_user_id = deps.user.id;
    }
    const result = await api.TodoTask.updateMany({ id: task.id, revision: input.expected_revision }, { $set: set, $inc: { revision: 1 } });
    if (result.updated !== 1) fail(409, "This task changed; reload before saving.");
    return { ok: true, task: { ...task, ...set, revision: input.expected_revision + 1 } };
  }

  async function archiveTask(api, caller, owner, input, deps) {
    if (!owner) fail(403, "Only Gabriel can archive tasks.");
    const id = idText(input.id, { required: true });
    if (!Number.isInteger(input.expected_revision) || input.expected_revision < 0) fail(400, "A current revision is required.");
    let task;
    try {
      task = await api.TodoTask.get(id);
    } catch {
      fail(404, "Task not found.");
    }
    if (task.revision !== input.expected_revision) fail(409, "This task changed; reload before saving.");
    const stamp = deps.now();
    const result = await api.TodoTask.updateMany(
      { id: task.id, revision: input.expected_revision },
      { $set: { archived_at: stamp, updated_at: stamp }, $inc: { revision: 1 } }
    );
    if (result.updated !== 1) fail(409, "This task changed; reload before saving.");
    return { ok: true };
  }

  async function accountOptions(api, owner, isOwnerFn) {
    if (!owner) fail(403, "Only Gabriel can manage team accounts.");
    const users = await api.User.list("id", MAX_USERS, 0);
    const members = await api.TeamMember.list("id", MAX_LIST_LIMIT, 0);
    const linkByUser = new Map();
    for (const m of members) for (const uid of m.auth_user_ids || []) linkByUser.set(uid, m.id);
    const accounts = users.map((u) => ({
      id: u.id,
      full_name: u.full_name || "",
      email: u.email || "",
      owner_account: isOwnerFn(u) === true,
      member_id: linkByUser.get(u.id) || null,
    }));
    return { ok: true, accounts };
  }

  async function manageMember(api, caller, owner, input, deps) {
    if (!owner) fail(403, "Only Gabriel can manage team members.");
    requestKey(input.request_key);
    if (caller.management_lock) fail(409, "A previous write needs review before members change.");
    const display_name = text(input.display_name, 120, { required: true });
    const active = input.active === true;
    const ids = Array.isArray(input.auth_user_ids) ? input.auth_user_ids.map((v) => idText(v)) : null;
    if (!ids) fail(400, "Invalid account links.");
    if (new Set(ids).size !== ids.length) fail(400, "Duplicate account links.");
    const members = await api.TeamMember.list("id", MAX_LIST_LIMIT, 0);
    const root = members.find((m) => m.member_key === "gabriel");
    const rootIds = new Set(root ? root.auth_user_ids || [] : []);
    const linkConflict = (selfId) => {
      for (const uid of ids) {
        if (rootIds.has(uid)) fail(409, "Owner accounts stay on Gabriel's record.");
        const other = members.find((m) => m.id !== selfId && Array.isArray(m.auth_user_ids) && m.auth_user_ids.includes(uid));
        if (other) fail(409, "That sign-in account is already linked to another person.");
      }
    };
    const memberId = text(input.id, 120);
    if (memberId === "") {
      const dupe = members.find(
        (m) => m.display_name === display_name && JSON.stringify([...(m.auth_user_ids || [])].sort()) === JSON.stringify([...ids].sort())
      );
      if (dupe) return { ok: true, member: dupe, duplicate: true };
      linkConflict(null);
      const row = {
        member_key: slugify(display_name) + "-" + deps.uuid().slice(0, 8),
        display_name,
        auth_user_ids: ids,
        active,
        revision: 0,
        management_lock: "",
        seed_state: "pending",
        seed_completed_at: "",
      };
      let created;
      try {
        created = await api.TeamMember.create(row);
      } catch {
        try {
          await api.TeamMember.updateMany({ id: caller.id }, { $set: { management_lock: "unreconciled-" + deps.uuid() } });
        } catch {}
        fail(500, "The member save result is uncertain and was locked for review.");
      }
      return { ok: true, member: created };
    }
    const member = members.find((m) => m.id === memberId);
    if (!member) fail(404, "Person not found.");
    if (member.member_key === "gabriel") fail(403, "Gabriel's record cannot be edited here.");
    if (!Number.isInteger(input.revision) || input.revision !== member.revision) fail(409, "This person changed; reload before saving.");
    linkConflict(member.id);
    const result = await api.TeamMember.updateMany(
      { id: member.id, revision: member.revision },
      { $set: { display_name, active, auth_user_ids: ids }, $inc: { revision: 1 } }
    );
    if (result.updated !== 1) fail(409, "This person changed; reload before saving.");
    return { ok: true, member: { ...member, display_name, active, auth_user_ids: ids, revision: member.revision + 1 } };
  }

  return async function handler(req) {
    try {
      if (req.method !== "POST") return reply({ error: "POST requests only." }, 405);
      let body;
      try {
        body = await req.json();
      } catch {
        return reply({ error: "Invalid request body." }, 400);
      }
      if (!body || typeof body !== "object" || Array.isArray(body)) return reply({ error: "Invalid request body." }, 400);
      const client = await getClient(req);
      let user = null;
      try {
        user = await client.auth.me();
      } catch {
        user = null;
      }
      if (!user || !user.id) return reply({ error: "Sign in required." }, 401);
      const api = client.asServiceRole.entities;
      const members = await api.TeamMember.list("id", MAX_LIST_LIMIT, 0);
      const linked = members.filter((m) => Array.isArray(m.auth_user_ids) && m.auth_user_ids.includes(user.id));
      if (linked.length > 1) return reply({ error: "This sign-in is linked to more than one person and needs review." }, 409);
      if (linked.length === 0) return reply({ error: "This sign-in has no to-do access." }, 403);
      const caller = linked[0];
      if (caller.active !== true) return reply({ error: "This person is inactive." }, 403);
      const ownerByEmail = isOwner(user) === true;
      if (ownerByEmail && caller.member_key !== "gabriel") return reply({ error: "Owner account link needs review." }, 409);
      const owner = ownerByEmail && caller.member_key === "gabriel";
      const deps = { user, now, uuid };
      const action = text(body.action, 40, { required: true });
      switch (action) {
        case "access":
          return reply({ ok: true, allowed: true, owner, member_id: caller.id });
        case "list":
          return reply(await listTasks(api, caller, owner, body));
        case "board":
          return reply(await boardTasks(api, caller, owner, body));
        case "get":
          return reply(await getTask(api, caller, owner, body));
        case "create":
          return reply(await createTask(api, caller, owner, body, deps));
        case "update_task":
          return reply(await updateTask(api, caller, owner, body, deps));
        case "archive":
          return reply(await archiveTask(api, caller, owner, body, deps));
        case "account_options":
          return reply(await accountOptions(api, owner, isOwner));
        case "manage_member":
          return reply(await manageMember(api, caller, owner, body, deps));
        default:
          return reply({ error: "Unknown action." }, 400);
      }
    } catch (e) {
      const status = Number.isInteger(e?.status) && e.status >= 400 && e.status < 600 ? e.status : 500;
      return reply({ error: String(e?.message || "Request failed.").slice(0, 300) }, status);
    }
  };
}

// Owner check mirrors src/lib/agentCenterAccess.js (isAgentCenterOwner).
// Gabriel's two sign-ins are the only owner accounts: team views, assigning
// tasks to others, and member management. Everyone else sees only their own list.
const OWNER_EMAILS = new Set(["gabefronk@gmail.com", "gabriel.fronk.wd@gmail.com"]);
const isOwner = (user) => user?.role === "admin" && OWNER_EMAILS.has(String(user?.email || "").trim().toLowerCase());

Deno.serve(createTodoHandler({ getClient: async (req) => createClientFromRequest(req), isOwner }));
