import {useState} from 'react';
import {Copy, Pencil, Search, Trash2} from 'lucide-react';
import {colorParts, selectedSeries} from './amscoConfiguratorModel';
const money=value=>typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value):'—';
const action='inline-flex min-h-11 min-w-11 items-center justify-center rounded px-2 text-[#305367] hover:bg-[#e6eef3] disabled:opacity-40';
const label=price=>price?.status==='priced'?(price.price_source==='amsco_source_engine'?'Pricebook calculated':'AMSCO verified'):price?.status==='amsco_lookup_needed'?'AMSCO lookup':price?.status==='native_unavailable'?'Pricing unavailable':['calculating','native_busy'].includes(price?.status)?'Calculating…':'Not priced';
export default function AmscoQuoteSchedule({lines,settings,prices=[],disabled,onEdit,onCopy,onRemove}) {
  const [search,setSearch]=useState(''),[condensed,setCondensed]=useState(true);
  const rows=lines.map((line,index)=>({line,index,price:prices[index]})).filter(({line})=>[line.style,line.room,line.mark,line.width+' x '+line.height].join(' ').toLowerCase().includes(search.toLowerCase()));
  const buttons=(line,index)=><div className="flex justify-end"><button type="button" className={action} disabled={disabled} onClick={()=>onEdit(line,index)} aria-label={'Edit window '+(index+1)} title="Edit"><Pencil size={16}/></button><button type="button" className={action} disabled={disabled} onClick={()=>onCopy(line)} aria-label={'Duplicate window '+(index+1)} title="Duplicate"><Copy size={16}/></button><button type="button" className={action+' text-[#914438]'} disabled={disabled} onClick={()=>onRemove(index)} aria-label={'Remove window '+(index+1)} title="Remove"><Trash2 size={16}/></button></div>;
  const details=line=>{const color=colorParts(line.options,settings);return [selectedSeries(line),color.exterior+' exterior / '+color.interior+' interior',line.options?.glass||settings.glass,line.options?.tempered?'Tempered':null,line.options?.grilles].filter(Boolean).join(' · ');};
  return <div className="overflow-hidden rounded-lg border border-[#bdcbd4] bg-white">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#cad5dd] bg-[#edf2f5] px-3 py-2"><label className="flex min-h-11 items-center gap-2 text-xs text-[#3e5d6f]"><input type="checkbox" checked={condensed} onChange={e=>setCondensed(e.target.checked)} className="h-4 w-4 accent-[#196c86]"/>Condensed view</label><label className="flex min-h-11 min-w-0 items-center gap-2 rounded border border-[#bccbd4] bg-white px-3"><Search size={15} className="text-[#6d8390]"/><input aria-label="Filter quote line items" type="search" placeholder="Filter line items" value={search} onChange={e=>setSearch(e.target.value)} className="w-40 min-w-0 bg-transparent text-base outline-none sm:text-sm"/></label></div>
    <div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-xs"><thead className="border-b border-[#cad5dd] bg-[#f8fafb] text-[#60798a]"><tr>{['Line / product','Room','Qty','List','Dealer','Customer','Extended',''].map((heading,i)=><th key={i} className={'px-3 py-3 font-semibold '+(i>1?'text-right':'')}>{heading}</th>)}</tr></thead><tbody>{rows.map(({line,index,price})=><tr key={line.id||index} className="border-b border-[#e2e9ee] align-top last:border-0 hover:bg-[#f8fafb]"><td className="min-w-40 px-3 py-3"><div className="text-[10px] font-semibold text-[#748a97]">{(index+1)*100}{line.mark?' · '+line.mark:''}</div><button type="button" disabled={disabled} onClick={()=>onEdit(line,index)} className="mt-1 text-left font-semibold text-[#196c86] hover:underline disabled:opacity-60">{line.style}</button><p className="mt-1 text-[#466475]">{line.width} × {line.height} in · {line.dimension_basis==='frame'?'Frame':line.dimension_basis==='call'?'Call':'Rough opening'}</p><p className={'mt-2 text-[10px] '+(price?.status==='priced'?'text-[#287358]':'text-[#976819]')}>{label(price)}</p>{!condensed&&<p className="mt-2 max-w-sm leading-relaxed text-[#6a8190]">{details(line)}</p>}</td><td className="max-w-32 break-words px-3 py-4 text-[#466475]">{line.room||'—'}</td><td className="px-3 py-4 text-right tabular-nums">{line.qty}</td>{['list','dealer','customer'].map(kind=><td key={kind} className="whitespace-nowrap px-3 py-4 text-right tabular-nums">{money(price?.unit_prices?.[kind])}</td>)}<td className="whitespace-nowrap px-3 py-4 text-right font-semibold tabular-nums text-[#215d48]">{money(price?.line_totals?.customer)}</td><td className="px-1 py-2">{buttons(line,index)}</td></tr>)}</tbody></table></div>
    <div className="divide-y divide-[#dbe4eb] md:hidden">{rows.map(({line,index,price})=><article key={line.id||index} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-semibold text-[#748a97]">LINE {(index+1)*100}{line.mark?' · '+line.mark:''}</p><button type="button" onClick={()=>onEdit(line,index)} disabled={disabled} className="mt-1 min-h-11 text-left text-sm font-semibold text-[#196c86]">{line.style}</button><p className="text-sm text-[#466475]">{line.width} × {line.height} in · {line.dimension_basis}</p><p className="mt-1 text-xs text-[#6a8190]">{line.room||'Location not set'}</p></div><span className="shrink-0 rounded bg-[#e8f0f5] px-2 py-1 text-xs text-[#466475]">Qty {line.qty}</span></div>{!condensed&&<p className="mt-3 text-xs leading-relaxed text-[#6a8190]">{details(line)}</p>}<dl className="mt-3 grid grid-cols-3 gap-2 border-y border-[#e2e9ee] py-3 text-xs">{[['List',price?.unit_prices?.list],['Dealer',price?.unit_prices?.dealer],['Customer',price?.unit_prices?.customer]].map(([name,value])=><div key={name}><dt className="text-[10px] text-[#718996]">{name} / each</dt><dd className="mt-1 font-semibold tabular-nums text-[#305367]">{money(value)}</dd></div>)}</dl><div className="mt-2 flex flex-wrap items-center justify-between gap-2"><p className="text-xs text-[#60798a]">{label(price)}<strong className="mt-1 block text-base text-[#215d48]">{money(price?.line_totals?.customer)} total</strong></p>{buttons(line,index)}</div></article>)}</div>
    {!rows.length&&<p className="px-4 py-8 text-center text-sm text-[#718996]">{lines.length?'No line items match your filter.':'Add a window or use the AI guide to build this quote.'}</p>}
  </div>;
}
