import { useMemo } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { INSTALL_CATALOG, calculateInstall, installLineKey, installOptions, resolveInstallSelection } from '../../../base44/shared/installBudget.js';
import { inputClass, secondaryClass } from './TakeoffEditor';

export const installMoney = value => value == null || !Number.isFinite(value) ? '—' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
const materialNames = { vinyl: 'Vinyl', composite: 'Composite / fiberglass', wood: 'Wood / aluminum' };
function Field({ label, children }) { return <label className="block min-w-0"><span className="mb-1.5 block text-xs font-semibold text-[#535E72]">{label}</span>{children}</label>; }
function MaterialSelect({ value, onChange, disabled }) { return <select className={inputClass} value={value} onChange={e => onChange(e.target.value)} disabled={disabled}>{Object.entries(materialNames).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select>; }
const amount = (label, value) => <div className="flex flex-wrap justify-between gap-2 py-1.5"><dt className="text-[#616D81]">{label}</dt><dd className="font-semibold tabular-nums">{installMoney(value)}</dd></div>;

export function InstallTotals({ summary, linked = false }) {
  if (!summary?.enabled) return null;
  return <section aria-label="Installation totals" className="rounded-xl border border-[#C3D4EE] bg-[#F2F6FC] p-4">
    <h3 className="font-semibold text-[#131A26]">Installation budget</h3>
    {!summary.complete ? <div role="alert" className="mt-3 rounded-lg bg-[#FCF5E9] p-3 text-sm text-[#8A5A10]"><p className="font-semibold">Complete these install details</p><ul className="mt-2 list-disc space-y-1 pl-5">{summary.issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></div> : <>
      <dl className="mt-3 text-sm">{amount('Install sale · non-taxable', summary.sell)}{amount('Installer / sub pay', summary.cost)}{summary.extra_sell > 0 && amount('Additional material / equipment sale', summary.extra_sell)}{linked && amount('Window quote total', summary.product_sell)}{linked && <div className="mt-2 border-t border-[#C3D4EE] pt-2">{amount('Customer total with installation', summary.customer_total)}</div>}</dl>
      {summary.margin != null && <p className="mt-2 text-xs text-[#616D81]">Install margin {(summary.margin * 100).toFixed(1)}%</p>}
      {summary.budget ? <details className="mt-4 border-t border-[#C3D4EE] pt-3"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Material and job budget</summary><dl className="text-sm">{amount('Product cost', summary.budget.product_cost)}{amount('Material overhead', summary.budget.material_overhead)}{amount('Use tax', summary.budget.use_tax)}{amount('Material cost with tax', summary.budget.material_cost)}{amount('Target material sale', summary.budget.material_target_sell)}{amount('Additional job overhead', summary.budget.second_overhead)}{amount('Total job cost', summary.budget.total_cost)}{amount('Target job sale', summary.budget.target_sale)}{amount('Budgeted profit at quoted sale', summary.budget.profit)}</dl><p className="mt-2 text-xs">Job margin {summary.budget.margin == null ? '—' : (summary.budget.margin * 100).toFixed(1) + '%'}</p><p className="mt-2 text-xs text-[#616D81]">Overhead units: {summary.budget.overhead_units.toFixed(2)}. Target material sale uses the budget margin. The saved window quote keeps its original product price.</p></details> : <p className="mt-3 text-xs text-[#616D81]">Enter product cost below to calculate material tax, overhead, and total job margin.</p>}
    </>}
  </section>;
}

export default function InstallBudgetEditor({ lines = [], config, onChange, onLinesChange, context = {}, disabled = false, standalone = false }) {
  const summary = useMemo(() => calculateInstall(lines, config, context), [lines, config, context]);
  const update = patch => onChange({ ...config, ...patch });
  const select = (key, patch) => update({ selections: { ...config.selections, [key]: { ...(config.selections?.[key] || {}), ...patch } } });
  const changeLine = (index, patch) => onLinesChange(lines.map((line, i) => i === index ? { ...line, ...patch } : line));
  const changeFinance = patch => update({ finance: { ...config.finance, ...patch } });
  return <div className="space-y-4">
    <label className="flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border border-[#DDE3EC] bg-white p-4"><input type="checkbox" className="h-5 w-5 accent-[#2A5EA8]" checked={config.enabled} onChange={e => update({ enabled: e.target.checked })} disabled={disabled} /><span><span className="block text-sm font-semibold">Include installation</span><span className="mt-1 block text-xs text-[#616D81]">Calculate the selected openings using the 2026 BFS sale and sub-pay rates.</span></span></label>
    {config.enabled && <>
      <div className="grid gap-3 sm:grid-cols-2"><Field label="Default material"><MaterialSelect value={config.material} disabled={disabled} onChange={material => update({ material, method: 'standard' })} /></Field><Field label="Default install method"><select className={inputClass} value={config.method} disabled={disabled} onChange={e => update({ method: e.target.value })}><option value="standard">1F RB405 standard{config.material === 'wood' ? ' · with sill pan' : ' · no sill pan'}</option>{installOptions(config.material, 'window', 'method').map(rate => <option key={rate.id} value={rate.id}>{rate.label}</option>)}</select></Field></div>
      <p className="text-xs leading-relaxed text-[#616D81]">Sizes use the quote’s measurement basis. Area = width × height ÷ 144 for inches. AMSCO black/bronze exterior screw adders apply automatically. Door rates require a panel or system selection.</p>
      <div className="space-y-3">{lines.map((line, index) => {
        const s = resolveInstallSelection(line, index, config), result = summary.lines.find(item => item.key === s.key);
        const selectedRate = INSTALL_CATALOG.rates.find(r => r.id === s.rate_id);
        const kind = selectedRate?.kind || (/door|bifold|multislide|pivot|lfg/i.test(line.style || line.label || '') ? 'door' : 'window');
        const methods = installOptions(s.material, kind, 'method');
        return <article key={s.key} className="rounded-xl border border-[#DDE3EC] bg-white p-3 sm:p-4">
          <div className="flex items-start justify-between gap-3"><label className="flex min-h-11 items-center gap-2 text-sm font-semibold"><input type="checkbox" className="h-4 w-4 accent-[#2A5EA8]" checked={s.enabled} disabled={disabled} onChange={e => select(s.key, { enabled: e.target.checked })} />{line.mark || line.label || `Opening ${index + 1}`}{line.style ? ` · ${line.style}` : ''}</label>{standalone && <button type="button" aria-label={`Remove opening ${index + 1}`} className={secondaryClass} disabled={disabled} onClick={() => { const selections = { ...config.selections }; delete selections[s.key]; update({ selections }); onLinesChange(lines.filter((_, i) => i !== index)); }}><Trash2 size={15} /></button>}</div>
          {standalone ? <div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-4"><Field label="Opening / room"><input className={inputClass} value={line.label || ''} disabled={disabled} onChange={e => changeLine(index, { label: e.target.value })} /></Field><Field label={selectedRate?.unit === 'panel' ? 'Panel quantity' : selectedRate?.unit === 'system' ? 'System quantity' : 'Opening quantity'}><input type="number" min="1" max="1000" className={inputClass} value={line.qty} disabled={disabled} onChange={e => changeLine(index, { qty: e.target.value })} /></Field><Field label="Width (inches)"><input type="number" min="0.01" step="any" className={inputClass} value={line.width} disabled={disabled} onChange={e => changeLine(index, { width: e.target.value })} /></Field><Field label="Height (inches)"><input type="number" min="0.01" step="any" className={inputClass} value={line.height} disabled={disabled} onChange={e => changeLine(index, { height: e.target.value })} /></Field></div> : <p className="text-xs text-[#616D81]">Qty {line.qty} · {line.width} × {line.height} {line.units || 'in'}{result?.sqft != null ? ` · ${result.sqft.toFixed(2)} sq ft each` : ''}</p>}
          {s.enabled && <>
            <div className="mt-3 grid gap-3 sm:grid-cols-3"><Field label="Material"><MaterialSelect value={s.material} disabled={disabled} onChange={material => select(s.key, { material, method: 'standard', rate_id: '', adders: [] })} /></Field><Field label="Base install rate"><select className={inputClass} disabled={disabled} value={s.rate_id} onChange={e => select(s.key, { rate_id: e.target.value, material: s.material, method: 'standard', adders: [] })}><option value="">Automatic window size band</option>{INSTALL_CATALOG.rates.filter(r => r.category === 'base' && r.material === s.material).map(rate => <option value={rate.id} key={rate.id}>{rate.label} · {installMoney(rate.sell)} / {rate.unit}</option>)}</select></Field><Field label="Install method"><select className={inputClass} value={s.method} disabled={disabled} onChange={e => select(s.key, { method: e.target.value })}><option value="standard">Standard 1F RB405{s.material === 'wood' ? ' + sill pan' : ''}</option>{!methods.some(r => r.id === s.method) && s.method !== 'standard' && <option value={s.method}>Choose a compatible method</option>}{methods.map(rate => <option value={rate.id} key={rate.id}>{rate.label}</option>)}</select></Field></div>
            {kind === 'door' && <p className="mt-2 text-xs text-[#8A5A10]">Confirm quantity counts {selectedRate?.unit || 'panels or systems'} for this rate. Add knockdown frames, pockets and glazing separately below.</p>}
            {context.linked && kind === 'door' && <div className="mt-3 max-w-xs"><Field label="Confirmed install panel / system quantity"><input className={inputClass} type="number" min="1" max="1000" value={s.billing_qty ?? ''} disabled={disabled} placeholder={String(line.qty)} onChange={e => select(s.key, { billing_qty: e.target.value })} /></Field></div>}
            <details className="mt-3"><summary className="min-h-11 cursor-pointer py-2 text-xs font-semibold text-[#535E72]">Per-opening adders and rate detail</summary><div className="grid gap-2 sm:grid-cols-2">{installOptions(s.material, kind, 'adder').filter(rate => rate.unit === 'opening').map(rate => <label key={rate.id} className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={s.adders.includes(rate.id) || result?.auto_adder === rate.id} disabled={disabled || result?.auto_adder === rate.id} onChange={e => select(s.key, { adders: e.target.checked ? [...s.adders, rate.id] : s.adders.filter(id => id !== rate.id) })} /><span>{rate.label} · {installMoney(rate.sell)}{result?.auto_adder === rate.id ? ' · automatic' : ''}</span></label>)}</div>{result?.charges?.map(rate => <p className="mt-2 text-xs text-[#616D81]" key={rate.id}>{rate.label}: sale {installMoney(rate.sell)} / cost {installMoney(rate.cost)} · {rate.source.sell} / {rate.source.cost}</p>)}</details>
            {result?.issues?.length ? <p className="mt-2 text-xs text-[#8A5A10]">{result.issues.join(' ')}</p> : result && <div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 border-t border-[#E9EDF4] pt-3 text-sm"><span>Install sale <strong>{installMoney(result.sell_each)} each</strong></span><span>Line total <strong>{installMoney(result.sell)}</strong></span><span className="text-[#616D81]">Cost {installMoney(result.cost)}</span></div>}
          </>}
        </article>;
      })}</div>
      {standalone && <button type="button" className={secondaryClass} disabled={disabled} onClick={() => onLinesChange([...lines, { id: crypto.randomUUID(), label: '', qty: 1, width: '', height: '', units: 'in' }])}><Plus size={15} />Add opening</button>}
      <details className="rounded-xl border border-[#DDE3EC] bg-white p-4" open={config.extras?.length > 0}><summary className="min-h-11 cursor-pointer text-sm font-semibold">Additional panels, knockdown frames and job charges</summary><div className="space-y-3">{(config.extras || []).map((extra, index) => <div key={index} className="flex flex-wrap items-end gap-2"><div className="min-w-0 flex-1"><Field label="Charge"><select className={inputClass} value={extra.rate_id} disabled={disabled} onChange={e => update({ extras: config.extras.map((item, i) => i === index ? { ...item, rate_id: e.target.value } : item) })}>{INSTALL_CATALOG.rates.filter(r => r.category !== 'method').map(rate => <option key={rate.id} value={rate.id}>{rate.material} · {rate.label} · {installMoney(rate.sell)} / {rate.unit}</option>)}</select></Field></div><div className="w-24"><Field label="Quantity"><input className={inputClass} type="number" min="1" max="1000" value={extra.qty} disabled={disabled} onChange={e => update({ extras: config.extras.map((item, i) => i === index ? { ...item, qty: e.target.value } : item) })} /></Field></div><button type="button" aria-label={`Remove additional charge ${index + 1}`} className={secondaryClass} disabled={disabled} onClick={() => update({ extras: config.extras.filter((_, i) => i !== index) })}><Trash2 size={15} /></button></div>)}<button type="button" className={secondaryClass} disabled={disabled} onClick={() => update({ extras: [...(config.extras || []), { rate_id: 'vf-window-adder-43', qty: 1 }] })}><Plus size={15} />Add charge</button></div></details>
      <InstallTotals summary={summary} linked={context.linked} />
      <details className="rounded-xl border border-[#DDE3EC] bg-white p-4"><summary className="min-h-11 cursor-pointer text-sm font-semibold">Material cost, tax, margin and overhead</summary><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[['product_cost', 'True product cost including delivery'], ['extra_material', 'Additional install materials'], ['equipment', 'Additional equipment'], ['tax_rate', 'Use tax (%)'], ['material_margin', 'Target material margin (%)'], ['labor_margin', 'Target labor margin (%)']].map(([key, label]) => <Field key={key} label={label}><input type="number" className={inputClass} min="0" step="any" max={key.includes('margin') ? '99.99' : undefined} value={config.finance?.[key] ?? ''} placeholder={key === 'product_cost' && context.product_cost != null ? String(context.product_cost) : undefined} disabled={disabled} onChange={e => changeFinance({ [key]: e.target.value })} /></Field>)}<Field label="Labor sale basis"><select className={inputClass} value={config.finance?.labor_mode || 'rates'} disabled={disabled} onChange={e => changeFinance({ labor_mode: e.target.value })}><option value="rates">Workbook sale rates</option><option value="margin">Sub pay ÷ (1 − labor margin)</option></select></Field><Field label="Overhead calculation"><select className={inputClass} value={config.finance?.overhead_mode || 'workbook'} disabled={disabled} onChange={e => changeFinance({ overhead_mode: e.target.value })}><option value="workbook">Workbook · 20% twice</option><option value="once">20% once</option></select></Field></div><p className="mt-3 text-xs leading-relaxed text-[#616D81]">Defaults: 7.45% use tax, 30% material margin and 27% labor margin. Listed install sale rates apply unless the labor margin basis is selected. Blank product cost uses the linked dealer cost when available; confirm delivery is included. Only additional materials and equipment entered here add to the window quote’s existing product sale.</p></details>
      <details className="text-xs leading-relaxed text-[#616D81]"><summary className="min-h-11 cursor-pointer py-3 font-semibold">Price sheet notes</summary><ul className="list-disc space-y-2 pl-5">{INSTALL_CATALOG.notes.map(note => <li key={note}>{note}</li>)}</ul></details>
    </>}
  </div>;
}
