import { useMemo, useRef, useState } from "react";
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, Copy, FileSpreadsheet, Loader2, Pencil, Plus, Send, Settings2, Sparkles, Trash2, X } from "lucide-react";
import { base44 } from "@/api/base44Client";
import { initialQuoteFormValues, loadQuotePreferences } from "@/lib/windowQuotePreferences";
import { STANDARD_STUDIO_PROFILE } from "@/lib/easyRequest";
import { inputClass, secondaryClass } from "./TakeoffEditor";
import { parseTakeoff, CSV_TEMPLATE } from "./takeoff";
import { STYLE_CHOICES, createBuilderLine, duplicateBuilderLine, parseTradeCode, formatTradeCode, buildBuilderPreview } from "./windowBuilderModel";
import ProWindowDiagram from "./ProWindowDiagram";

const primary = "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[#2A5EA8] px-4 py-3 text-sm font-semibold text-white hover:bg-[#234F8E] disabled:cursor-not-allowed disabled:opacity-50";
const panel = "min-w-0 rounded-2xl border border-[#DDE3EC] bg-white";
const issueText = item => typeof item === "string" ? item : item?.message || "Review this selection.";
const errorText = e => e?.response?.data?.error || e?.response?.data?.message || e.message || "Could not complete that step. Your windows are still here.";
const styleCode = style => /single.?hung/i.test(style) ? "SH" : /slider|vent/i.test(style) ? "XO" : /picture|direct.?set/i.test(style) ? "FX" : "";
const styleDescription = style => /single.?hung/i.test(style) ? "Bottom sash opens" : /slider|vent/i.test(style) ? "Horizontal sliding window" : /picture|direct.?set/i.test(style) ? "Fixed glass, no opening sash" : "Describe the product with AI";
const own = (object, key) => Object.prototype.hasOwnProperty.call(object || {}, key);
const optionLabels = { series: "Series / frame", fin: "Installation fin", color: "Color", exterior_color: "Exterior color", interior_color: "Interior color", glass: "Glass coating", tempered: "Tempered", patterned_glass: "Privacy texture", screen: "Screen", hardware: "Hardware", hardware_color: "Hardware color", glass_thickness: "Glass thickness", glazing_method: "Glazing", elevation: "Installation elevation", argon: "Argon", super_spacer: "Super Spacer", capillary_tubes: "Capillary tubes", grilles: "Grilles", operation: "Operation", sash_split: "Sash split", number_wide: "Number wide", unit_type: "Unit type", viewing_direction: "Viewing direction" };
const optionValue = value => typeof value === "boolean" ? value ? "Yes" : "No" : String(value);
function Field({ label, children, note }) { return <label className="block min-w-0"><span className="mb-1.5 block text-xs font-semibold text-[#535E72]">{label}</span>{children}{note && <span className="mt-1.5 block text-xs leading-relaxed text-[#77839A]">{note}</span>}</label>; }
function Issues({ items = [] }) { return items.length ? <ul className="list-disc space-y-1 pl-4 text-sm leading-relaxed">{items.map((item, i) => <li key={i}>{issueText(item)}</li>)}</ul> : null; }
function MiniWindow({ line }) { const code = styleCode(line.style); return <div className="flex h-28 w-20 shrink-0 items-center justify-center rounded-xl bg-[#F6F8FC]" aria-label={`${line.style || "Window"} style illustration`}>{code ? <span aria-hidden="true"><ProWindowDiagram code={code} width={Number(line.width) || 36} height={Number(line.height) || 60} forQuoteThumbnail /></span> : <Plus size={24} className="text-[#77839A]" />}</div>; }
function WindowCard({ line, index, settings, onEdit, onCopy, onRemove, disabled, compact = false }) {
  const options = line.options || {}, code = formatTradeCode(Number(line.width), Number(line.height));
  const special = [options.fin, options.tempered === true || options.tempered === "true" ? "Tempered" : null, options.patterned_glass && options.patterned_glass !== "None" ? options.patterned_glass : null].filter(Boolean);
  return <article className="min-w-0 rounded-xl border border-[#DDE3EC] bg-white p-3 sm:p-4">
    <div className="flex min-w-0 gap-3"><MiniWindow line={line} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-2"><h3 className="min-w-0 max-w-full [overflow-wrap:anywhere] text-sm font-semibold text-[#131A26]">{line.mark || `Window ${index + 1}`} · {line.style}</h3><span className="rounded-md bg-[#E7EEFA] px-2 py-1 text-xs font-semibold text-[#1E4A85]">Qty {line.qty}</span></div><p className="mt-1 min-w-0 max-w-full [overflow-wrap:anywhere] text-base font-semibold text-[#131A26]">{line.width} × {line.height} in{code && line.dimension_basis === "call" ? <span className="ml-2 text-xs font-normal text-[#616D81]">{code}</span> : null}</p><p className="mt-1 min-w-0 max-w-full [overflow-wrap:anywhere] text-xs leading-relaxed text-[#616D81]">{line.dimension_basis === "call" ? "Call size" : line.dimension_basis === "frame" ? "Actual frame size" : "Rough opening"}{line.room ? ` · ${line.room}` : ""}</p><p className="mt-2 break-words text-xs leading-relaxed text-[#535E72]">{[options.color || settings.color || "Color to choose", options.glass || settings.glass || "Glass to choose", ...special].join(" · ")}</p></div></div>
    {Object.keys(options).length > 0 && <details className="mt-3 border-t border-[#E9EDF4] pt-1"><summary className="min-h-11 cursor-pointer py-3 text-xs font-semibold text-[#535E72]">Configuration details</summary><dl className="grid gap-x-4 gap-y-2 pb-2 text-xs sm:grid-cols-2">{Object.entries(options).filter(([, value]) => value !== undefined && value !== null && value !== "").map(([key, value]) => <div key={key} className="min-w-0"><dt className="text-[#77839A]">{optionLabels[key] || key.replaceAll("_", " ")}</dt><dd className="mt-0.5 break-words font-medium text-[#535E72]">{optionValue(value)}</dd></div>)}</dl></details>}
    {!compact && <div className="mt-3 flex flex-wrap gap-2 border-t border-[#E9EDF4] pt-2"><button type="button" className={secondaryClass} disabled={disabled} onClick={onEdit} aria-label={`Edit window ${index + 1}`}><Pencil size={14} />Edit</button><button type="button" className={secondaryClass} disabled={disabled} onClick={onCopy} aria-label={`Duplicate window ${index + 1}`}><Copy size={14} />Duplicate</button><button type="button" className="ml-auto flex min-h-11 items-center gap-1.5 px-2 text-xs text-[#8A4038] disabled:opacity-50" disabled={disabled} onClick={onRemove} aria-label={`Remove window ${index + 1}`}><Trash2 size={14} />Remove</button></div>}
  </article>;
}

export default function WindowQuoteBuilder({ seed, preferenceUserId, busy = false, saveError = "", onSave, onCancel }) {
  const [defaults] = useState(() => initialQuoteFormValues(seed, loadQuotePreferences(preferenceUserId)));
  const [title, setTitle] = useState(seed?.title || "");
  const [settings, setSettings] = useState(defaults.settings);
  const [source, setSource] = useState(seed?.source || {});
  const [lines, setLines] = useState(() => structuredClone(seed?.lines || []));
  const [useStandard, setUseStandard] = useState(defaults.use_standard);
  const [editor, setEditor] = useState(seed?.lines?.length ? null : { index: -1, line: createBuilderLine("Studio Single Hung") });
  const [tradeCode, setTradeCode] = useState("");
  const [error, setError] = useState("");
  const [step, setStep] = useState("build");
  const [processing, setProcessing] = useState("");
  const [reviewed, setReviewed] = useState(null);
  const [confirmed, setConfirmed] = useState(false);
  const [aiOpen, setAiOpen] = useState(false);
  const [aiText, setAiText] = useState("");
  const [conversation, setConversation] = useState([]);
  const [suggestion, setSuggestion] = useState(null);
  const [importOpen, setImportOpen] = useState(false);
  const [importText, setImportText] = useState("");
  const upload = useRef(null), requestId = useRef(crypto.randomUUID());
  const disabled = busy || !!processing;
  const standardSource = useMemo(() => ({ ...source, easy_request: { profile_id: STANDARD_STUDIO_PROFILE.id, profile_revision: STANDARD_STUDIO_PROFILE.revision, confirmed: useStandard, dimension_basis: "call", units: "in" } }), [source, useStandard]);
  const normalizedSettings = useMemo(() => ({ ...settings, gross_margin: settings.gross_margin === "" || settings.gross_margin == null ? null : Number(settings.gross_margin) }), [settings]);
  const preview = useMemo(() => buildBuilderPreview(normalizedSettings, lines, standardSource), [normalizedSettings, lines, standardSource]);
  const count = lines.reduce((sum, line) => sum + (Number(line.qty) || 0), 0);
  const draft = () => ({ title: title.trim(), settings: normalizedSettings, lines: lines.map(line => Object.fromEntries(Object.entries(line).filter(([key]) => key !== "source_reference"))), source: { easy_request: standardSource.easy_request } });
  const invalidate = () => { setReviewed(null); setConfirmed(false); setSuggestion(current => current ? { ...current, stale: true } : null); setError(""); };
  const changeSettings = patch => { invalidate(); setSettings(current => ({ ...current, ...patch })); };
  const changeEditor = patch => { invalidate(); setEditor(current => ({ ...current, line: { ...current.line, ...patch } })); };
  const changeOption = (key, value) => { const options = { ...editor.line.options }; if (value === "") delete options[key]; else options[key] = value; changeEditor({ options }); };
  const startEditor = (line, index = -1) => { invalidate(); setEditor({ index, line: structuredClone(line) }); setTradeCode(line.dimension_basis === "call" ? formatTradeCode(Number(line.width), Number(line.height)) : ""); };
  const addWindow = () => {
    const line = editor.line;
    if (!line.style?.trim() || [line.width, line.height].some(value => value === "" || !Number.isFinite(Number(value)) || Number(value) <= 0) || !Number.isInteger(Number(line.qty)) || Number(line.qty) <= 0) { setError("Choose a style, enter a positive width and height, and use a whole-number quantity."); return; }
    const saved = { ...line, width: Number(line.width), height: Number(line.height), qty: Number(line.qty), units: "in" };
    invalidate(); setLines(current => editor.index < 0 ? [...current, saved] : current.map((item, index) => index === editor.index ? saved : item)); setEditor(null); setTradeCode("");
  };
  const applyTradeCode = () => { const parsed = parseTradeCode(tradeCode); if (!parsed.ok) { setError((parsed.issues || []).map(issueText).join(" ") || "Enter a four-digit call code, such as 3050 or 5050."); return; } changeEditor({ width: parsed.width, height: parsed.height, units: "in", dimension_basis: "call" }); };
  const editorHasChanges = () => editor && (editor.line.style !== "Studio Single Hung" || editor.line.dimension_basis !== "call" || tradeCode.trim() || Number(editor.line.qty) !== 1 || [editor.line.width, editor.line.height, editor.line.room, editor.line.mark].some(value => value !== "" && value !== null && value !== undefined) || Object.keys(editor.line.options || {}).length > 0 || editor.index >= 0);
  const canReplaceSchedule = () => { if (editorHasChanges()) { setError("Add this window to the quote or cancel its edit first, so none of your changes are lost."); return false; } if (conversation.length || suggestion || aiText.trim()) { setError("Apply or discard the proposed AI changes before importing a schedule."); return false; } return true; };
  const importSchedule = (value, filename = "") => { if (!canReplaceSchedule()) return; try { const parsed = parseTakeoff(value, filename); if (parsed.errors?.length) throw new Error(parsed.errors.join(" ")); invalidate(); setLines(parsed.lines); setSource(current => ({ ...current, ...parsed.source })); setEditor(null); setImportOpen(false); } catch (e) { setError(errorText(e)); } };
  const readFile = async event => { const file = event.target.files?.[0]; event.target.value = ""; if (!file || !canReplaceSchedule()) return; if (!/\.(csv|json)$/i.test(file.name) || file.size > 2000000) { setError("Choose a CSV or JSON schedule under 2 MB."); return; } setProcessing("import"); try { importSchedule(await file.text(), file.name); } catch (e) { setError(errorText(e)); } finally { setProcessing(""); } };
  const builderCall = async body => { const response = await base44.functions.invoke("windowQuoteBuilder", body); if (response.data?.error) throw new Error(response.data.error); return response.data; };
  const askAI = async event => {
    event?.preventDefault(); if (!aiText.trim() || disabled) return;
    if (editorHasChanges()) { setError("Add this window to the quote or cancel its edit before asking the AI guide, so it can see the complete schedule."); return; }
    if (editor) setEditor(null);
    const next = [...conversation, { role: "user", content: aiText.trim() }];
    setProcessing("assist"); setError("");
    try { const result = await builderCall({ action: "assist", draft: suggestion?.stale ? draft() : suggestion?.draft || draft(), conversation: next, unresolved_requirements: suggestion?.review?.unresolved_requirements || [] }); setSuggestion(result); setConversation([...next, { role: "assistant", content: result.assistant_message || "Review the window details below." }]); setAiText(""); }
    catch (e) { setError(errorText(e)); } finally { setProcessing(""); }
  };
  const applySuggestion = () => {
    if (!suggestion?.review?.ready || suggestion.stale || editorHasChanges()) return; if (aiText.trim()) { setError("Send or clear your new AI message before applying the earlier proposal."); return; }
    invalidate(); setLines(suggestion.draft.lines); setSettings(suggestion.draft.settings); setSource(suggestion.draft.source || {}); setEditor(null); setConversation([]); setSuggestion(null); setAiText(""); setAiOpen(false);
  };
  const review = async () => {
    if (disabled) return;
    if (editor) { setError("Add this window to the quote, or cancel its edit, before reviewing the package."); return; }
    if (!lines.length) { setError("Add at least one window first."); return; }
    if (conversation.length || suggestion || aiText.trim()) { setAiOpen(true); setError("Apply the AI's proposed schedule or discard its proposed changes before reviewing."); return; }
    setProcessing("review"); setError("");
    try { const result = await builderCall({ action: "review", draft: draft() }); setReviewed(result); setStep("review"); setConfirmed(false); }
    catch (e) { setError(errorText(e)); } finally { setProcessing(""); }
  };
  const saveDraft = () => { if (editor) { setError("Add this window to the quote, or cancel its edit, before saving."); return; } if (conversation.length || suggestion || aiText.trim()) { setError("Apply or discard the proposed AI changes before saving the draft."); return; } if (!lines.length) { setError("Add a window before saving this draft."); return; } onSave({ request_id: requestId.current, ...draft(), message: "" }, false); };
  const price = () => {
    if (!reviewed?.review?.ready || !confirmed || disabled) return;
    const accepted = reviewed.draft;
    onSave({ request_id: requestId.current, title: title.trim(), settings: accepted.settings, lines: accepted.lines, message: "", source: { ...accepted.source, visual_builder: { version: 1, confirmed: true, schedule_hash: reviewed.review.schedule_hash } } }, true);
  };
  const aiReady = !suggestion?.stale && suggestion?.review?.ready && !(suggestion.review.questions?.length || suggestion.review.product_review?.length || suggestion.review.unresolved_requirements?.length);
  const shownLines = step === "review" ? reviewed?.draft?.lines || lines : lines;
  return <div className="min-w-0 pb-4">
    <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><button type="button" className="mb-2 inline-flex min-h-11 items-center gap-2 text-sm font-medium text-[#1E4A85]" disabled={disabled} onClick={onCancel}><ArrowLeft size={16} />All quotes</button><div className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#77839A]">Glass Forge · Window Quote Pro</div><h1 className="mt-1 text-2xl font-semibold tracking-tight text-[#131A26] sm:text-3xl">{step === "build" ? "Build your window quote" : "Review your windows"}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-[#616D81]">{step === "build" ? "Choose your windows or describe them to AI. Standard options are already handled." : "Confirm the schedule, then let AMSCO build and verify the price."}</p></div><div className="flex items-center gap-2 text-xs font-semibold"><span className={`rounded-full px-3 py-2 ${step === "build" ? "bg-[#E7EEFA] text-[#1E4A85]" : "bg-[#EAF5EE] text-[#276449]"}`}>1 · Build</span><ArrowRight size={14} className="text-[#77839A]" /><span className={`rounded-full px-3 py-2 ${step === "review" ? "bg-[#E7EEFA] text-[#1E4A85]" : "bg-white text-[#77839A]"}`}>2 · Review</span><ArrowRight size={14} className="text-[#77839A]" /><span className="text-[#77839A]">3 · Price</span></div></div>
    {(error || saveError) && <div role="alert" className="mb-4 rounded-xl border border-[#EFD2CA] bg-[#FBEDEA] p-4 text-sm text-[#8A4038]">{error || saveError}</div>}
    {suggestion?.stale && <div className="mb-4 rounded-xl border border-[#EEDAB4] bg-[#FCF5E9] p-4 text-sm text-[#8A5A10]">Your windows changed after the AI's proposal. Send the guide a follow-up to update its proposal, or discard those proposed changes.</div>}
    {step === "build" ? <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="min-w-0 space-y-4">
        <section className={panel + " p-4 sm:p-5"}><div className="grid gap-4 sm:grid-cols-2"><Field label="Quote / project name"><input className={inputClass} placeholder="e.g. Lakeview · Lot 216" maxLength={180} value={title} disabled={disabled} onChange={e => setTitle(e.target.value)} /></Field><div className="flex items-end"><button className={secondaryClass + " w-full"} disabled={disabled} onClick={() => setAiOpen(value => !value)}><Sparkles size={17} className="text-[#2A5EA8]" />{aiOpen ? "Hide AI guide" : "Describe windows with AI"}</button></div></div><details className="mt-4 border-t border-[#E9EDF4] pt-1"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 text-sm font-medium text-[#535E72]"><Settings2 size={15} />Quote defaults<span className="ml-auto break-words text-right text-xs font-normal">{settings.color || "Choose color"} · {settings.glass || "Choose glass"}</span><ChevronDown size={14} /></summary><div className="mt-2 grid gap-3 sm:grid-cols-2"><Field label="Default color"><select className={inputClass} value={settings.color || ""} disabled={disabled} onChange={e => changeSettings({ color: e.target.value })}><option value="White">White inside & outside</option><option value="Taupe">Taupe inside & outside</option><option value="Black exterior / White interior">Black outside / white inside</option>{settings.color && !["White", "Taupe", "Black exterior / White interior"].includes(settings.color) && <option value={settings.color}>{settings.color}</option>}</select></Field><Field label="Default glass"><select className={inputClass} value={settings.glass || ""} disabled={disabled} onChange={e => changeSettings({ glass: e.target.value })}><option value="CozE (LowE)">CozE (Low-E)</option>{settings.glass && settings.glass !== "CozE (LowE)" && <option value={settings.glass}>{settings.glass}</option>}</select></Field></div><label className="mt-3 flex min-h-11 items-start gap-2 py-2 text-sm text-[#535E72]"><input type="checkbox" className="mt-0.5 h-5 w-5 shrink-0 accent-[#2A5EA8]" checked={useStandard} disabled={disabled} onChange={e => { invalidate(); setUseStandard(e.target.checked); }} /><span>Use standard Studio options for unspecified choices<span className="mt-1 block text-xs leading-relaxed text-[#77839A]">Standard screens on opening windows. AMSCO selects the required glass construction for each size.</span></span></label></details></section>
        {aiOpen && <section className={panel + " overflow-hidden"} aria-label="AI window guide"><div className="flex items-center gap-2 border-b border-[#DDE3EC] bg-[#F2F6FC] px-4 py-4"><Sparkles size={18} className="text-[#2A5EA8]" /><h2 className="font-semibold text-[#131A26]">AI window guide</h2></div><div className="space-y-3 p-4"><p className="text-sm leading-relaxed text-[#616D81]">Paste a customer's message, ask about a choice, or describe changes. You review the proposed windows before anything is priced.</p>{!conversation.length && <button className="min-h-11 rounded-lg border border-[#DDE3EC] px-3 py-2 text-left text-xs text-[#1E4A85]" disabled={disabled} onClick={() => setAiText("One 5050 slider and one 5060 slider, white with standard options")}>Try: “One 5050 slider and one 5060 slider…”</button>}{conversation.map((entry, index) => <div key={index} className={`rounded-xl p-3 text-sm leading-relaxed ${entry.role === "user" ? "ml-5 bg-[#E7EEFA] text-[#131A26]" : "mr-2 bg-[#F6F8FC] text-[#535E72]"}`}><span className="mb-1 block text-[10px] font-semibold uppercase tracking-wide text-[#77839A]">{entry.role === "user" ? "You" : "AI guide"}</span><p className="whitespace-pre-wrap break-words">{entry.content}</p></div>)}{aiReady && <div className="space-y-3 rounded-xl border border-[#BFDCCA] bg-[#F1F8F3] p-3"><p className="text-sm font-semibold text-[#276449]">Proposed schedule · {suggestion.draft.lines.length} lines</p>{suggestion.draft.lines.map((line, index) => <p key={index} className="text-sm text-[#535E72]">{line.qty} × {line.style} · {line.width} × {line.height} in</p>)}<button className={primary} disabled={disabled} onClick={applySuggestion}><Check size={16} />Use these windows</button></div>}<form onSubmit={askAI} className="flex items-end gap-2"><Field label="Message the AI guide"><textarea aria-label="Message the AI guide" className={inputClass + " min-h-24 resize-y"} placeholder="What windows do you need?" maxLength={12000} value={aiText} disabled={disabled} onChange={e => setAiText(e.target.value)} /></Field><button type="submit" className={primary + " shrink-0 px-3"} disabled={!aiText.trim() || disabled} aria-label="Ask AI guide">{processing === "assist" ? <Loader2 size={17} className="animate-spin" /> : <Send size={17} />}</button></form>{(conversation.length > 0 || suggestion) && <button type="button" className="min-h-11 text-xs text-[#8A4038]" disabled={disabled} onClick={() => { setConversation([]); setSuggestion(null); setAiText(""); setError(""); }}>Discard proposed AI changes</button>}</div></section>}
        {editor && <section className={panel + " p-4 sm:p-5"} aria-label="Window editor"><div className="mb-4 flex items-center justify-between gap-2"><h2 className="text-base font-semibold text-[#131A26]">{editor.index < 0 ? "Add a window" : `Edit window ${editor.index + 1}`}</h2><button type="button" className="flex min-h-11 min-w-11 items-center justify-center rounded-lg text-[#616D81]" aria-label="Cancel window edit" disabled={disabled} onClick={() => { setEditor(null); setError(""); }}><X size={18} /></button></div><fieldset disabled={disabled}><legend className="mb-2 text-xs font-semibold text-[#535E72]">Window style</legend><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{STYLE_CHOICES.map(choice => <button type="button" key={choice.value} aria-pressed={editor.line.style === choice.value} onClick={() => changeEditor({ style: choice.value })} className={`flex min-h-32 flex-col items-center justify-center gap-2 rounded-xl border p-3 text-center text-xs font-semibold ${editor.line.style === choice.value ? "border-[#2A5EA8] bg-[#E7EEFA] text-[#1E4A85]" : "border-[#DDE3EC] bg-white text-[#535E72]"}`}><span className="flex h-14 items-center justify-center" aria-hidden="true">{styleCode(choice.value) ? <ProWindowDiagram code={styleCode(choice.value)} size={38} width={48} height={48} /> : <Plus size={27} />}</span>{choice.label}</button>)}</div><p className="mt-2 text-xs text-[#77839A]">{styleDescription(editor.line.style)}</p></fieldset>{!STYLE_CHOICES.slice(0, 3).some(item => item.value === editor.line.style) && <div className="mt-3"><Field label="Requested product"><input className={inputClass} value={editor.line.style === "Custom" ? "" : editor.line.style} placeholder="e.g. Hampton casement" disabled={disabled} onChange={e => changeEditor({ style: e.target.value || "Custom" })} /></Field><p className="mt-2 text-xs text-[#8A5A10]">This product needs a quoting review. The AI guide can help organize the request.</p></div>}
          <div className="mt-5 rounded-xl bg-[#F6F8FC] p-3 sm:p-4"><div className="flex items-end gap-2"><div className="min-w-0 flex-1"><Field label="Quick call code" note="3050 = 36 × 60 in · 5050 = 60 × 60 in"><input className={inputClass} inputMode="numeric" value={tradeCode} maxLength={4} placeholder="e.g. 5050" disabled={disabled} onChange={e => setTradeCode(e.target.value)} onKeyDown={e => { if (e.key === "Enter") { e.preventDefault(); applyTradeCode(); } }} /></Field></div><button type="button" className={secondaryClass + " mb-6 shrink-0"} disabled={disabled || !tradeCode.trim()} onClick={applyTradeCode}>Use size</button></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3"><Field label="Width (in)"><input className={inputClass} type="number" inputMode="decimal" min="0.001" step="any" value={editor.line.width ?? ""} disabled={disabled} onChange={e => { setTradeCode(""); changeEditor({ width: e.target.value }); }} /></Field><Field label="Height (in)"><input className={inputClass} type="number" inputMode="decimal" min="0.001" step="any" value={editor.line.height ?? ""} disabled={disabled} onChange={e => { setTradeCode(""); changeEditor({ height: e.target.value }); }} /></Field><Field label="Quantity"><input className={inputClass} type="number" inputMode="numeric" min="1" max="1000" step="1" value={editor.line.qty ?? 1} disabled={disabled} onChange={e => changeEditor({ qty: e.target.value })} /></Field></div><div className="mt-3"><Field label="These measurements are"><select className={inputClass} value={editor.line.dimension_basis || "call"} disabled={disabled} onChange={e => changeEditor({ dimension_basis: e.target.value })}><option value="call">Call size</option><option value="frame">Actual frame size — needs review</option><option value="rough_opening">Rough opening — needs review</option></select></Field></div></div>
          <div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Room / location (optional)"><input className={inputClass} value={editor.line.room || ""} placeholder="e.g. Kitchen" maxLength={250} disabled={disabled} onChange={e => changeEditor({ room: e.target.value })} /></Field><Field label="Window mark (optional)"><input className={inputClass} value={editor.line.mark || ""} placeholder="e.g. W1" maxLength={100} disabled={disabled} onChange={e => changeEditor({ mark: e.target.value })} /></Field></div>
          <details className="mt-4 rounded-xl border border-[#DDE3EC] px-3"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-2 text-sm font-medium text-[#535E72]">Change this window's options<ChevronDown size={16} /></summary><div className="grid gap-3 pb-4 sm:grid-cols-2"><Field label="Color"><select className={inputClass} value={editor.line.options?.color || ""} disabled={disabled} onChange={e => changeOption("color", e.target.value)}><option value="">Use quote default · {settings.color}</option><option value="White">White</option><option value="Taupe">Taupe</option><option value="Black exterior / White interior">Black outside / white inside</option>{editor.line.options?.color && !["White", "Taupe", "Black exterior / White interior"].includes(editor.line.options.color) && <option value={editor.line.options.color}>{editor.line.options.color}</option>}</select></Field><Field label="Installation fin"><select className={inputClass} value={editor.line.options?.fin || ""} disabled={disabled} onChange={e => changeOption("fin", e.target.value)}><option value="">Standard nail fin</option><option value="Nail Fin">Nail fin</option><option value="Flush Fin">Flush fin</option>{editor.line.options?.fin && !["Nail Fin", "Flush Fin"].includes(editor.line.options.fin) && <option value={editor.line.options.fin}>{editor.line.options.fin}</option>}</select></Field><Field label="Tempered glass"><select className={inputClass} value={own(editor.line.options, "tempered") ? String(editor.line.options.tempered) : ""} disabled={disabled} onChange={e => changeOption("tempered", e.target.value === "" ? "" : e.target.value === "true")}><option value="">Standard non-tempered</option><option value="false">Non-tempered</option><option value="true">Tempered</option></select></Field><Field label="Privacy texture"><select className={inputClass} value={editor.line.options?.patterned_glass || ""} disabled={disabled} onChange={e => changeOption("patterned_glass", e.target.value)}><option value="">Standard · no texture</option><option value="None">No texture</option><option value="Obscure">Obscure</option>{editor.line.options?.patterned_glass && !["None", "Obscure"].includes(editor.line.options.patterned_glass) && <option value={editor.line.options.patterned_glass}>{editor.line.options.patterned_glass}</option>}</select></Field></div><p className="pb-3 text-xs leading-relaxed text-[#77839A]">Options depend on the product and size. Other glass, colors, screens, or special requirements can be described to the AI guide.</p></details><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="max-w-sm text-xs leading-relaxed text-[#77839A]">Style illustrations help identify the window. AMSCO confirms the actual configuration.</p><button type="button" className={primary} disabled={disabled} onClick={addWindow}><Plus size={16} />{editor.index < 0 ? "Add to quote" : "Save window"}</button></div>
        </section>}
        <section className="space-y-3" aria-label="Your window schedule"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold text-[#131A26]">Your windows</h2><p className="mt-1 text-xs text-[#616D81]">{lines.length} lines · {count} windows</p></div><button type="button" className={secondaryClass} disabled={disabled || !!editor || lines.length >= 200} onClick={() => startEditor(createBuilderLine("Studio Single Hung"))}><Plus size={15} />Add window</button></div>{!lines.length && <p className="rounded-xl border border-dashed border-[#CBD4E1] px-4 py-7 text-center text-sm text-[#77839A]">Add your first window above, or let the AI guide build the schedule.</p>}{lines.map((line, index) => <WindowCard key={line.id || index} line={line} index={index} settings={settings} disabled={disabled || !!editor} onEdit={() => startEditor(line, index)} onCopy={() => { invalidate(); setLines(current => [...current, duplicateBuilderLine(line)]); }} onRemove={() => { invalidate(); setLines(current => current.filter((_, i) => i !== index)); }} />)}<div className="flex flex-wrap gap-2"><button type="button" className="inline-flex min-h-11 items-center gap-2 text-xs font-medium text-[#1E4A85]" disabled={disabled} onClick={() => setImportOpen(value => !value)}><FileSpreadsheet size={15} />Import a schedule</button></div>{importOpen && <div className={panel + " space-y-3 p-4"}><Field label="Paste CSV or JSON schedule"><textarea className={inputClass + " min-h-32 font-mono"} placeholder={CSV_TEMPLATE} value={importText} disabled={disabled} onChange={e => setImportText(e.target.value)} /></Field><p className="text-xs text-[#616D81]">Import replaces the current unsaved schedule. Review the resulting windows before pricing.</p><div className="flex flex-wrap gap-2"><button className={secondaryClass} disabled={disabled || !importText.trim()} onClick={() => importSchedule(importText)}>Import text</button><button className={secondaryClass} disabled={disabled} onClick={() => upload.current?.click()}>Choose CSV / JSON</button><input ref={upload} type="file" accept=".csv,.json" className="hidden" onChange={readFile} aria-label="Import window schedule file" /></div></div>}</section>
      </div>
      <aside className={panel + " p-4 sm:p-5 xl:sticky xl:top-5"} aria-label="Quote summary"><div className="flex items-center gap-2"><CheckCircle2 size={20} className="text-[#2A5EA8]" /><h2 className="text-base font-semibold text-[#131A26]">Quote summary</h2></div><p className="mt-4 text-3xl font-semibold text-[#131A26]">{count}<span className="ml-2 text-sm font-normal text-[#616D81]">windows</span></p><p className="mt-3 text-sm leading-relaxed text-[#616D81]">Build the package here. Final pricing comes from a saved, checked AMSCO quote.</p><div className="my-4 rounded-xl bg-[#F6F8FC] p-3 text-xs leading-relaxed text-[#535E72]">Standard construction options stay with AMSCO. You only need to change the choices specific to this job.</div>{lines.length > 0 && !preview.ok && <details className="mb-4 text-[#8A5A10]"><summary className="min-h-11 cursor-pointer py-3 text-sm font-medium">Selections to review</summary><Issues items={preview.questions || preview.issues || []} /></details>}<details className="border-t border-[#E9EDF4]"><summary className="flex min-h-12 cursor-pointer items-center justify-between text-sm font-medium text-[#535E72]">Pricing settings<ChevronDown size={15} /></summary><div className="space-y-3 pb-4"><Field label="Dealer account"><select className={inputClass} value={settings.dealer || ""} disabled={disabled} onChange={e => changeSettings({ dealer: e.target.value })}><option value="BFS">BFS</option><option value="BTB">BTB / B2B — needs review</option></select></Field><Field label="Shipping yard"><select className={inputClass} value={settings.yard || ""} disabled={disabled} onChange={e => changeSettings({ yard: e.target.value })}><option value="BFS-UTAH DESIGN(11)">BFS · Utah Design (11)</option>{settings.yard && settings.yard !== "BFS-UTAH DESIGN(11)" && <option value={settings.yard}>{settings.yard}</option>}</select></Field><Field label="Gross margin (%)"><input className={inputClass} type="number" inputMode="decimal" min="0" max="99.99" step="any" value={settings.gross_margin ?? ""} disabled={disabled} onChange={e => changeSettings({ gross_margin: e.target.value })} /></Field></div></details><div className="mt-3 space-y-2"><button type="button" className={primary + " w-full"} disabled={disabled || !lines.length} onClick={review}>{processing === "review" ? <Loader2 size={16} className="animate-spin" /> : <ArrowRight size={16} />}Review windows</button><button type="button" className={secondaryClass + " w-full"} disabled={disabled || !lines.length} onClick={saveDraft}>Save draft</button></div><p className="mt-3 text-xs leading-relaxed text-[#77839A]">You choose when to request pricing. Building and AI guidance do not create an AMSCO quote.</p></aside>
    </div> : <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="min-w-0 space-y-3"><div className={panel + " p-4"}><h2 className="text-lg font-semibold text-[#131A26]">{title || "Window quote"}</h2><p className="mt-1 text-sm text-[#616D81]">{shownLines.length} lines · {shownLines.reduce((sum, line) => sum + Number(line.qty || 0), 0)} windows</p></div>{shownLines.map((line, index) => <WindowCard key={line.id || index} compact line={line} index={index} settings={reviewed.draft.settings} />)}{!reviewed.review.ready && <section className="rounded-xl border border-[#EEDAB4] bg-[#FCF5E9] p-4 text-[#8A5A10]"><h2 className="mb-2 font-semibold">These choices need review</h2><Issues items={[...(reviewed.review.questions || []), ...(reviewed.review.product_review || []), ...(reviewed.review.unresolved_requirements || [])]} /><p className="mt-3 text-sm">Go back to change the windows or ask the AI guide for help. Your requested choices stay in the schedule.</p></section>}</div><aside className={panel + " p-4 sm:p-5 xl:sticky xl:top-5"}><h2 className="text-base font-semibold text-[#131A26]">Ready for pricing?</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-[#77839A]">Dealer / yard</dt><dd className="mt-1 text-[#535E72]">{reviewed.draft.settings.dealer} · {reviewed.draft.settings.yard}</dd></div><div><dt className="text-xs text-[#77839A]">Gross margin</dt><dd className="mt-1 text-[#535E72]">{reviewed.draft.settings.gross_margin}%</dd></div></dl><div className="my-4 rounded-xl bg-[#F6F8FC] p-3 text-sm leading-relaxed text-[#535E72]">AMSCO will check availability, save the windows, and return verified prices. This can take a few minutes. You can leave the page while it runs.</div>{reviewed.review.ready && <label className="flex min-h-11 items-start gap-2 py-2 text-sm leading-relaxed text-[#131A26]"><input type="checkbox" className="mt-1 h-5 w-5 shrink-0 accent-[#2A5EA8]" checked={confirmed} disabled={disabled} onChange={e => setConfirmed(e.target.checked)} /><span>I checked the sizes, quantities, and requested options.</span></label>}<button type="button" className={primary + " mt-3 w-full"} disabled={disabled || !confirmed || !reviewed.review.ready} onClick={price}>{busy ? <Loader2 size={17} className="animate-spin" /> : <Send size={17} />}Get AMSCO price</button><button type="button" className={secondaryClass + " mt-2 w-full"} disabled={disabled} onClick={() => { setStep("build"); setConfirmed(false); }}><ArrowLeft size={15} />Back to builder</button></aside></div>}
  </div>;
}
