import {useEffect,useState} from "react";
import {base44} from "@/api/base44Client";
export default function CleanCalendar(){
 const [data,setData]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[brief,setBrief]=useState(""),[agentBusy,setAgentBusy]=useState(false);
 async function agentBrief(){setAgentBusy(true);setBrief("");try{const c=await base44.agents.createConversation({agent_name:"calendar_coordinator",metadata:{purpose:"single_run_calendar_brief"}});await base44.agents.addMessage(c,{role:"user",content:"Run the calendar comparison once for the latest available coverage. Give only counts, material conflicts and source limitations in at most five sentences, then stop."});for(let i=0;i<18;i++){await new Promise(r=>setTimeout(r,3000));const updated=await base44.agents.getConversation(c.id);const messages=updated?.messages||[];const last=messages[messages.length-1];const verifiedTool=messages.some(m=>(m.tool_calls||[]).some(t=>t.status==="success"));if(verifiedTool&&last?.role==="assistant"&&typeof last.content==="string"&&last.content.trim()&&!(last.tool_calls||[]).some(t=>t.status==="running")){setBrief(last.content);return;}}setBrief("The agent has not returned a final brief yet. The verified comparison below remains available.");}catch(e){setBrief(e.response?.data?.message||"The agent brief could not complete. The comparison below remains available.");}finally{setAgentBusy(false);}}
 async function load(){setBusy(true);setError("");try{const r=await base44.functions.invoke("reconcileInstallCalendar",{});setData(r.data);}catch(e){setError(e.response?.data?.error||"Calendar comparison is unavailable. Source calendars remain intact.");}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 return <section className="space-y-4"><div className="flex justify-between gap-4"><h1 className="text-xl font-semibold">My installation calendar</h1><button disabled={busy} onClick={load} className="border rounded px-3 py-2">{busy?"Comparing sources…":"Refresh comparison"}</button></div>
 <p className="text-sm">Jobs found in your Sales Tracker, with calendar sources and ProBuild reports together. Original records are preserved.</p>
 <button className="border rounded px-3 py-2" disabled={agentBusy||busy} onClick={agentBrief}>{agentBusy?"Agent preparing brief…":"Ask calendar agent for brief"}</button>{brief&&<p role="status" className="whitespace-pre-wrap border rounded p-3">{brief}</p>}
 {error&&<p role="alert">{error}</p>}
 {data&&<><p role="status">{data.range_start} through {data.range_end} · {data.counts.clean_events} calendar entries · {data.counts.merged_duplicates} confirmed duplicates combined · {data.counts.needs_review} need review</p>
 {(data.source_status.tracker_stale||data.source_status.outlook_stale)&&<p className="text-amber-700">A source is over 26 hours old. Refresh source data before relying on this comparison.</p>}
 <p className="text-xs">Tracker captured {new Date(data.source_status.tracker_captured_at).toLocaleString()}; Outlook captured {new Date(data.source_status.outlook_captured_at).toLocaleString()}. ProBuild reports loaded: {data.source_status.probuild_reports_loaded}.</p>
 <div className="space-y-3">{data.events.map((e,i)=><article key={i} className="border rounded-lg p-4 bg-white"><h2 className="font-semibold">{e.event_date} · {e.start_time||"All day"} · {e.job_name}</h2><p>{e.address}</p><p className="text-xs">{e.sources.map(s=>s.source).join(" + ")}</p>{e.warnings.map((w,j)=><p key={j} className="text-amber-700 text-sm">{w}</p>)}<details className="mt-2"><summary>Notes, orders and reports</summary>{e.sources.map((s,j)=><div key={j} className="mt-3"><b>{s.source}</b><p className="whitespace-pre-wrap">{s.scope_notes||"No source notes."}</p></div>)}<h3 className="font-semibold mt-3">Tracker arrival estimates</h3>{e.tracker_rows.map(r=><p key={r.source_row} className="text-sm">Lot {r.lot} · OE {r.oe||"—"} · PO {r.po||"—"} · estimated arrival {r.arrival_date||"not provided"} · {r.source_sheet} row {r.source_row}</p>)}<h3 className="font-semibold mt-3">ProBuild reports</h3>{e.reports.length?e.reports.map(r=><p key={r.post_id} className="whitespace-pre-wrap text-sm">{r.job_date}: {r.message||"Report without text."}</p>):<p className="text-sm">No linked report in the stored data. Completion is unverified.</p>}</details></article>)}</div>
 <details className="border rounded p-3"><summary>Needs review ({data.review.length})</summary><p className="text-sm">These entries could not be matched confidently. They have not been deleted or classified as somebody else's customers.</p>{data.review.map((e,i)=><p key={i} className="my-2">{e.event_date} · {e.job_name} · {e.source}<br/><small>{e.reason}</small></p>)}</details>
 <details className="border rounded p-3"><summary>Estimated arrivals ({data.arrivals.length}) — separate from installations</summary>{data.arrivals.map(r=><p key={r.source_row}>{r.arrival_date} · {r.builder} / {r.subdivision} / lot {r.lot} · OE {r.oe||"—"} · tracker row {r.source_row}</p>)}</details>
 <details className="border rounded p-3"><summary>Unlinked ProBuild reports ({data.report_review.length})</summary>{data.report_review.map(r=><p key={r.post_id}>{r.job_date} · {r.job_name}<br/>{r.message}</p>)}</details>
 <details className="border rounded p-3"><summary>General reminders ({data.hidden.length})</summary>{data.hidden.map((e,i)=><p key={i}>{e.event_date} · {e.job_name}</p>)}</details>
 <p className="text-xs">Calendar coordinator uses fixed matching rules for routine comparisons. Ambiguous items stay in review. Scheduled work, arrival estimates and report evidence are kept distinct.</p></>}
 </section>;
}