import {useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {Bot,LockKeyhole,RefreshCw,GitBranch,ShieldAlert,FileText,Clock3,PlugZap,CheckCircle2,RotateCcw,Unplug,ArrowUpRight} from "lucide-react";
import {base44} from "@/api/base44Client";
import {useAuth} from "@/lib/AuthContext";
import {isAgentCenterOwner} from "@/lib/agentCenterAccess";
const control="mt-2 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-[#2A5EA8]";
const when=v=>v?new Date(v).toLocaleString():"Not reported";
const tone=s=>s==="verified"||s==="connected"?"bg-emerald-50 text-emerald-700":s==="planned"||s==="manual"?"bg-slate-100 text-slate-700":/failed|decision|error/i.test(s)?"bg-amber-50 text-amber-800":"bg-blue-50 text-blue-700";
const label=s=>String(s||"").replaceAll("_"," ");
function Pill({value}){return <span className={"rounded-full px-2.5 py-1 text-xs font-medium "+tone(value)}>{label(value)}</span>}
export default function AdminAgentCenter(){
 const {user}=useAuth(),owner=isAgentCenterOwner(user);
 const [data,setData]=useState(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [target,setTarget]=useState("manager_agent"),[kind,setKind]=useState("request"),[title,setTitle]=useState(""),[body,setBody]=useState(""),[key,setKey]=useState(()=>crypto.randomUUID());
 const [resolution,setResolution]=useState({});
 const refresh=async()=>{setLoading(true);setError("");try{const r=await base44.functions.invoke("agentCenter",{action:"inventory"});setData(r.data)}catch(e){setError(e.response?.data?.error||"Agent Center is unavailable.")}finally{setLoading(false)}};
 useEffect(()=>{if(owner)refresh()},[owner]);
 const action=async(payload,success)=>{setBusy(payload.action+":"+ (payload.provider_id||payload.escalation_id||""));setError("");setNotice("");try{const r=await base44.functions.invoke("agentCenter",payload);setNotice(r.data?.message||r.data?.credential_flow||success);await refresh()}catch(e){setError(e.response?.data?.error||"The request could not be completed.")}finally{setBusy("")}};
 const save=async e=>{e.preventDefault();await action({action:"entry",target_id:target,kind,title,body,request_key:key},kind==="request"?"Request saved and added to Gabriel’s decision queue.":"Private entry saved.");setTitle("");setBody("");setKey(crypto.randomUUID())};
 if(!owner)return <div className="mx-auto max-w-lg p-8"><LockKeyhole className="mb-4 h-6 w-6 text-slate-500"/><h1 className="text-xl font-semibold">Owner access required</h1><p className="mt-2 text-sm text-slate-600">This workspace is private to the Glass Forge owner.</p></div>;
 const nodes=data?.inventory||[],entries=data?.entries||[],escalations=data?.escalations||[],connections=data?.connections||[],open=escalations.filter(x=>x.status==="needs_owner_decision"),manager=nodes.find(x=>x.id==="manager_agent"),children=nodes.filter(x=>x.parent_id==="manager_agent");
 return <div className="mx-auto max-w-7xl space-y-6 p-4 pb-32 text-[#131A26] sm:p-6">
  <header className="rounded-2xl bg-[#172438] p-5 text-white sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs uppercase tracking-widest text-slate-300"><LockKeyhole className="h-3.5 w-3.5"/>Private · Gabriel Fronk only</p><h1 className="mt-3 text-2xl font-semibold sm:text-3xl">Agent Center</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-slate-300">A control layer for agent ownership, status, handoffs, connections, and decisions.</p></div><button onClick={refresh} disabled={loading} className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-500 px-4 text-sm disabled:opacity-50"><RefreshCw className={"h-4 w-4 "+(loading?"animate-spin":"")}/>{loading?"Refreshing…":"Refresh"}</button></div><div className="mt-6 grid grid-cols-3 gap-3 border-t border-slate-600 pt-5">{[[nodes.length,"Agents"],[open.length,"Need your decision"],[connections.filter(x=>x.connection_state==="verified").length,"Verified connections"]].map(([n,l])=><div key={l}><p className="text-2xl font-semibold">{data?n:"—"}</p><p className="mt-1 text-xs text-slate-300">{l}</p></div>)}</div></header>
  {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{notice}</p>}
  <section><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><GitBranch className="h-5 w-5 text-[#2A5EA8]"/>Organization tree</h2><p className="mt-1 text-sm text-slate-600">Solid lines are reporting relationships. Handoff tags show cross-department coordination.</p></div><p className="text-xs text-slate-500">{data?"Checked "+when(data.checked_at):"Loading…"}</p></div>
   {manager&&<div className="rounded-2xl border border-[#B8CBE8] bg-[#F4F8FE] p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-[#172438] p-2.5 text-white"><Bot className="h-5 w-5"/></div><div><p className="text-xs font-medium uppercase tracking-wide text-[#2A5EA8]">{manager.department}</p><h3 className="font-semibold">{manager.name}</h3><p className="mt-1 max-w-2xl text-sm text-slate-700">{manager.assignment}</p></div></div><Pill value={manager.status}/></div><div className="mt-4 flex flex-wrap gap-2">{manager.capabilities.map(x=><span key={x} className="rounded-lg bg-white px-2.5 py-1.5 text-xs text-slate-700">{x}</span>)}</div></div>}
   <div className="mx-auto h-6 w-px bg-[#B8CBE8]"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{children.map(node=><article key={node.id} className="relative rounded-2xl border border-[#DDE3EC] bg-white p-5 shadow-sm before:absolute before:-top-6 before:left-1/2 before:h-6 before:w-px before:bg-[#B8CBE8]"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-wide text-[#2A5EA8]">{node.department}</p><h3 className="mt-1 font-semibold">{node.name}</h3><p className="mt-1 text-xs text-slate-500">{node.provider} · {node.host}</p></div><Pill value={node.connection}/></div><p className="mt-3 text-sm text-slate-700">{node.assignment}</p>{node.latest_update&&<p className="mt-3 rounded-lg bg-slate-50 p-2.5 text-xs text-slate-600">{node.latest_update}</p>}<div className="mt-4 flex flex-wrap gap-2">{node.handoffs.map(x=><span key={x} className="rounded-lg bg-[#EEF3FB] px-2 py-1 text-xs text-[#24538E]">↔ {x}</span>)}</div><div className="mt-4 flex items-center justify-between border-t pt-3 text-xs text-slate-500"><span>{node.status}</span>{node.url&&<Link to={node.url} className="flex items-center gap-1 text-[#2A5EA8]">Open <ArrowUpRight className="h-3.5 w-3.5"/></Link>}</div></article>)}</div>
  </section>
  <section className="rounded-2xl border border-[#DDE3EC] bg-white p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-semibold"><PlugZap className="h-5 w-5 text-[#2A5EA8]"/>Connections</h2><p className="mt-1 max-w-3xl text-sm text-slate-600">Provider profiles use a shared event format. Planned cards are not live. Credentials are never accepted into this page, entity records, logs, or browser storage.</p></div><Pill value="planned"/></div><div className="mt-5 grid gap-4 md:grid-cols-2">{connections.map(c=><article key={c.provider_id} className="rounded-xl border bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-medium">{c.provider_name}</h3><p className="mt-1 text-xs text-slate-500">{c.scope_summary}</p></div><Pill value={c.connection_state}/></div><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><div><dt className="text-slate-500">Method</dt><dd className="mt-1 font-medium">{label(c.auth_method)}</dd></div><div><dt className="text-slate-500">Last verified</dt><dd className="mt-1 font-medium">{when(c.last_verified_at)}</dd></div></dl><p className="mt-3 text-xs text-slate-600">{c.verification_message||"No secure connection has been configured."}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>action({action:"connection_prepare",provider_id:c.provider_id,scope_summary:c.scope_summary,auth_method:c.auth_method},"Connection profile prepared. Use Base44 secure secret storage or the provider’s OAuth flow to connect it.")} disabled={!!busy} className="min-h-10 rounded-lg border bg-white px-3 text-xs font-medium">Add / Replace secure setup</button><button onClick={()=>action({action:"connection_test",provider_id:c.provider_id},"No verified credential is configured, so this provider remains planned.")} disabled={!!busy} className="min-h-10 rounded-lg border bg-white px-3 text-xs font-medium"><CheckCircle2 className="mr-1 inline h-3.5 w-3.5"/>Test</button><button onClick={()=>action({action:"connection_disconnect",provider_id:c.provider_id},"Connection profile disconnected.")} disabled={!!busy} className="min-h-10 rounded-lg border bg-white px-3 text-xs font-medium"><Unplug className="mr-1 inline h-3.5 w-3.5"/>Disconnect</button></div></article>)}</div></section>
  <div className="grid items-start gap-5 xl:grid-cols-2"><section className="rounded-2xl border border-[#DDE3EC] bg-white p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><ShieldAlert className="h-5 w-5 text-[#2A5EA8]"/>Manager escalation queue</h2><p className="mt-2 text-sm text-slate-600">Unknown or consequential work waits here for your decision. The manager does not execute it.</p><ol className="mt-5 space-y-3">{!open.length&&<li className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-500">No decisions are waiting.</li>}{open.map(row=><li key={row.id} className="rounded-xl border bg-amber-50/40 p-4"><div className="flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{row.department}</span><time>{when(row.created_at)}</time></div><h3 className="mt-2 font-medium">{row.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{row.context}</p><textarea className={control+" min-h-20"} value={resolution[row.id]||""} onChange={e=>setResolution(s=>({...s,[row.id]:e.target.value}))} placeholder="Your decision or direction"/><button onClick={()=>action({action:"resolve_escalation",escalation_id:row.id,resolution:resolution[row.id]},"Decision recorded. No external action was taken.")} disabled={!resolution[row.id]?.trim()||!!busy} className="mt-3 min-h-10 rounded-lg bg-[#2A5EA8] px-3 text-xs font-medium text-white disabled:opacity-50">Record decision</button></li>)}</ol></section>
   <section className="rounded-2xl border border-[#DDE3EC] bg-white p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><FileText className="h-5 w-5 text-[#2A5EA8]"/>Request & notes</h2><p className="mt-2 text-sm text-slate-600">A request creates an owner escalation. Notes and recorded results stay private.</p><form className="mt-5 space-y-4" onSubmit={save}><label className="block text-sm font-medium">Agent<select className={control} value={target} onChange={e=>{setTarget(e.target.value);setKey(crypto.randomUUID())}}>{nodes.map(n=><option key={n.id} value={n.id}>{n.name}</option>)}</select></label><label className="block text-sm font-medium">Entry type<select className={control} value={kind} onChange={e=>{setKind(e.target.value);setKey(crypto.randomUUID())}}><option value="request">Request for manager review</option><option value="note">Private note</option><option value="result">Recorded result</option></select></label><label className="block text-sm font-medium">Title<input className={control} value={title} maxLength={160} required onChange={e=>{setTitle(e.target.value);setKey(crypto.randomUUID())}}/></label><label className="block text-sm font-medium">Details<textarea className={control+" min-h-32"} value={body} maxLength={5000} required onChange={e=>{setBody(e.target.value);setKey(crypto.randomUUID())}}/></label><button disabled={!title.trim()||!body.trim()||!!busy} className="min-h-11 w-full rounded-xl bg-[#2A5EA8] px-4 text-sm font-medium text-white disabled:opacity-50">{kind==="request"?"Save & escalate":"Save private entry"}</button></form></section></div>
  <section className="rounded-2xl border border-[#DDE3EC] bg-white p-5 sm:p-6"><h2 className="flex items-center gap-2 text-lg font-semibold"><Clock3 className="h-5 w-5 text-[#2A5EA8]"/>Activity history</h2><ol className="mt-4 space-y-3">{!entries.length&&<li className="rounded-xl border border-dashed p-5 text-center text-sm text-slate-500">No private activity has been recorded.</li>}{entries.map(e=><li key={e.id} className="rounded-xl border bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2 text-xs text-slate-500"><span>{label(e.kind)} · {nodes.find(n=>n.id===e.target_id)?.name||e.target_id}</span><time>{when(e.recorded_at)}</time></div><h3 className="mt-2 font-medium">{e.title}</h3><p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{e.body}</p></li>)}</ol></section>
 </div>
}