import {useCallback,useEffect,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {MessageSquare,RefreshCw,LockKeyhole,Paperclip,ArrowLeft,Link2} from 'lucide-react';
import {base44} from '@/api/base44Client';
import {useAuth} from '@/lib/AuthContext';
import {isAgentCenterOwner} from '@/lib/agentCenterAccess';
import {fetchReportFile,downloadFile} from '@/components/reports/reportExport';
import ConversationContacts from '@/components/contacts/ConversationContacts';
import MessageAssistantPanel,{BlueBubblesPanel} from '@/components/messages/MessageAssistantPanel';
const call=async data=>(await base44.functions.invoke('messages-bridge',data)).data;
const when=value=>value?new Date(value).toLocaleString():'Not yet';
const control='min-h-11 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm';
const attachmentLabel={pending:'Waiting for Mac',protected:'Open on approved device',too_large:'Open in Messages · over 8 MB',unavailable:'Not downloaded on Mac'};
export default function MessagesInbox(){
 const {user}=useAuth(),owner=isAgentCenterOwner(user),[params,setParams]=useSearchParams();
 const view=params.get('view')||'inbox';
 const selected=params.get('conversation')||'',jobFilter=params.get('job')||'',contactKey=params.get('contact')||'';
 const [contactFilter,setContactFilter]=useState(null);
 useEffect(()=>{let active=true;setContactFilter(null);if(owner&&contactKey)base44.functions.invoke('contacts-directory',{action:'contact',contact_key:contactKey}).then(r=>{if(active)setContactFilter(r.data.contact)}).catch(()=>{if(active)setError('This contact could not be loaded. Open Contacts and choose them again.')});return()=>{active=false}},[contactKey,owner]);
 const [data,setData]=useState(null),[detail,setDetail]=useState(null),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[jobSearch,setJobSearch]=useState(''),[jobs,setJobs]=useState([]),[job,setJob]=useState(''),[inboxSkip,setInboxSkip]=useState(0),[messageSkip,setMessageSkip]=useState(0),[linking,setLinking]=useState(false);
 const request=useRef(0),detailRequest=useRef(0);
 useEffect(()=>{request.current++;detailRequest.current++;setData(null);setDetail(null);setContactFilter(null);setJobs([]);},[user?.id,owner]);
 const refresh=useCallback(async()=>{if(contactKey&&contactFilter?.key!==contactKey)return;const id=++request.current;try{const result=await call({action:'inbox',search,job_id:jobFilter,skip:inboxSkip,...(contactKey?{contact_participants:[contactFilter.phone_key,contactFilter.email_key].filter(Boolean)}:{})});if(id===request.current){setData(result);setError('')}}catch(e){if(id===request.current){setData(null);setDetail(null);setError(e.response?.data?.error||'Messages are unavailable.')}}},[search,jobFilter,inboxSkip,contactKey,contactFilter]);
 const loadDetail=useCallback(async()=>{const id=++detailRequest.current;if(!selected){setDetail(null);return}try{const result=await call({action:'conversation',conversation_key:selected,skip:messageSkip});if(id===detailRequest.current){setDetail(result);setJob(result.conversation.job_id||'')}}catch(e){if(id===detailRequest.current){setDetail(null);setError(e.response?.data?.error||'Conversation could not be loaded.')}}},[selected,messageSkip]);
 useEffect(()=>{if(!owner)return;const timer=setTimeout(refresh,250);const poll=setInterval(refresh,15000);return()=>{clearTimeout(timer);clearInterval(poll)}},[owner,refresh]);
 useEffect(()=>{if(!owner)return;setDetail(null);loadDetail();const poll=setInterval(loadDetail,15000);return()=>{clearInterval(poll);detailRequest.current++}},[owner,loadDetail]);
 // Reviewing a thread preserves its unread state.
 const choose=key=>{setMessageSkip(0);setLinking(false);const next=new URLSearchParams(params);if(key)next.set('conversation',key);else next.delete('conversation');setParams(next)};
 const findJobs=async()=>{setBusy(true);try{const r=await call({action:'jobs',search:jobSearch});setJobs(r.jobs)}catch{setError('Jobs could not be loaded.')}finally{setBusy(false)}};
 const saveJob=async()=>{setBusy(true);try{await call({action:'link_job',conversation_key:selected,job_id:job});setLinking(false);await Promise.all([refresh(),loadDetail()])}catch{setError('Job link could not be saved.')}finally{setBusy(false)}};
 const openAttachment=async(m,a)=>{setBusy(true);try{const r=await call({action:'attachment',message_id:m.id,attachment_guid:a.guid});const blob=await fetchReportFile(r);downloadFile(new File([blob],r.name||a.name||'attachment',{type:blob.type}))}catch(e){setError(e.response?.data?.error||'Attachment could not be opened.')}finally{setBusy(false)}};
 const toggleDevice=async d=>{setBusy(true);try{await call({action:'set_device',device_id:d.device_id,enabled:!d.enabled});await refresh()}catch{setError('Connection could not be updated.')}finally{setBusy(false)}};
 if(!owner)return <div className="p-8"><LockKeyhole className="mb-3 h-6 w-6"/><h1 className="text-xl font-semibold">Private Messages</h1><p className="mt-2 text-slate-600">Only Gabriel’s owner accounts can open this inbox.</p></div>;
 const conversations=data?.conversations||[],devices=data?.devices||[];
 return <div className="mx-auto max-w-7xl space-y-5 p-4 pb-32 sm:p-6">
  <header className="rounded-2xl bg-[#172438] p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs uppercase tracking-widest text-slate-300"><LockKeyhole className="h-4 w-4"/>Private to Gabriel</p><h1 className="mt-3 flex items-center gap-2 text-2xl font-semibold"><MessageSquare className="h-6 w-6"/>Messages</h1><p className="mt-2 max-w-xl text-sm text-slate-300">Your conversations, job context and service follow-ups in one place.</p></div><button className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-500 px-4 text-sm" disabled={loading} onClick={async()=>{setLoading(true);await Promise.all([refresh(),loadDetail()]);setLoading(false)}}><RefreshCw className={'h-4 w-4 '+(loading?'animate-spin':'')}/>Refresh</button></div>
   {devices.map(d=>{const fresh=Date.now()-Date.parse(d.last_seen_at||'')<180000;return <div key={d.device_id} className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-slate-600 pt-4 text-xs"><div><strong className={d.enabled&&fresh&&d.source_ok?'text-emerald-300':'text-amber-200'}>{!d.enabled?'Sync paused':fresh&&d.source_ok?'Mac connected':fresh?'Messages source unavailable':'Waiting for Mac'}</strong><span className="ml-3 text-slate-300">Last check: {when(d.last_seen_at)} · {d.pending_count||0} pending</span>{d.last_error&&<p className="mt-1 text-amber-200">{d.last_error}</p>}</div><button disabled={busy} onClick={()=>toggleDevice(d)} className="min-h-10 rounded-lg border border-slate-500 px-3">{d.enabled?'Pause sync':'Resume sync'}</button></div>})}
   {!devices.length&&<p className="mt-4 text-sm text-amber-200">The Mac connection is being configured.</p>}
  </header>
  <nav aria-label="Message workspace" className="flex flex-wrap gap-2">{[['inbox','Job inbox'],['bluebubbles','BlueBubbles'],['assistant','Service assistant']].map(([key,label])=><button key={key} aria-pressed={view===key} className={'min-h-11 rounded-xl border px-4 text-sm font-medium '+(view===key?'border-teal-900 bg-teal-900 text-white':'border-slate-200 bg-white text-slate-700')} onClick={()=>{const next=new URLSearchParams(params);next.set('view',key);setParams(next)}}>{label}</button>)}</nav>
  {view==='bluebubbles'?<BlueBubblesPanel/>:view==='assistant'?<MessageAssistantPanel conversationKey={selected}/>:<>
  {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
  {contactKey&&<p className="text-sm">Showing messages for {contactFilter?.name||'this contact'}. <Link to="/contacts" className="text-blue-700 underline">Contacts</Link> · <Link to="/messages" className="text-blue-700 underline">Show all messages</Link></p>}
  {jobFilter&&<p className="text-sm">Showing messages linked to this job. <Link to="/messages" className="text-blue-700 underline">Show all</Link></p>}
  <div className="grid min-w-0 items-start gap-4 lg:grid-cols-[320px_minmax(0,1fr)]">
   <section aria-label="Conversations" className={(selected?'hidden lg:block ':'')+'min-w-0 rounded-2xl border bg-white p-4'}><label className="block text-sm font-medium">Find a conversation<input className={control+' mt-2 w-full'} placeholder="Name, phone, job or latest text" value={search} onChange={e=>{setSearch(e.target.value);setInboxSkip(0)}}/></label><div className="mt-4 space-y-2">{conversations.map(c=><button key={c.conversation_key} onClick={()=>choose(c.conversation_key)} className={'block w-full rounded-xl border p-3 text-left '+(selected===c.conversation_key?'border-blue-300 bg-blue-50':'border-slate-100 hover:bg-slate-50')}><span className="flex items-center justify-between gap-2"><strong className="break-words text-sm">{c.title}</strong>{(!c.last_read_at||c.last_message_at>c.last_read_at)&&<span aria-label="Unread" className="h-2 w-2 shrink-0 rounded-full bg-blue-600"/>}</span><p className="mt-1 line-clamp-2 break-words text-xs text-slate-600">{c.last_text}</p>{c.job_name&&<p className="mt-2 text-xs font-medium text-blue-700">{c.job_name}</p>}<time className="mt-2 block text-[11px] text-slate-400">{when(c.last_message_at)}</time></button>)}{data&&!conversations.length&&<p className="py-8 text-center text-sm text-slate-500">{contactKey?'No synced messages from this contact yet.':search?'No matching conversations.':'Your next text will appear here. Sync starts when the Mac connection is activated.'}</p>}</div><div className="mt-4 flex justify-between gap-2">{inboxSkip>0&&<button className={control} onClick={()=>setInboxSkip(n=>Math.max(0,n-100))}>Previous</button>}{data?.has_more&&<button className={control} onClick={()=>setInboxSkip(n=>n+100)}>More conversations</button>}</div></section>
   <section aria-label="Conversation" className={(!selected?'hidden lg:block ':'')+'min-w-0 rounded-2xl border bg-white p-4 sm:p-5'}>{!selected?<div className="py-24 text-center text-slate-500"><MessageSquare className="mx-auto mb-3 h-8 w-8"/><p>Choose a conversation to review its messages.</p><p className="mt-2 text-sm">Files and job links stay with that conversation.</p></div>:!detail?<p className="py-12 text-center text-slate-500">Loading conversation…</p>:<>
    <button className="mb-4 flex min-h-10 items-center gap-2 text-sm text-blue-700 lg:hidden" onClick={()=>choose('')}><ArrowLeft className="h-4 w-4"/>Conversations</button>
    <div className="flex flex-wrap items-start justify-between gap-3 border-b pb-4"><div className="min-w-0"><h2 className="break-words text-lg font-semibold">{detail.conversation.title}</h2><p className="mt-1 break-words text-xs text-slate-500">{detail.conversation.participants?.join(', ')}</p>{detail.conversation.job_id&&<Link className="mt-2 block text-sm font-medium text-blue-700" to={'/jobs/'+detail.conversation.job_id}>{detail.conversation.job_name}</Link>}</div><button className={control+' flex items-center gap-2'} onClick={()=>setLinking(!linking)}><Link2 className="h-4 w-4"/>{detail.conversation.job_id?'Change job':'Link a job'}</button></div>
    <Link className="my-3 inline-flex min-h-11 items-center rounded-xl border bg-blue-50 px-4 text-sm font-medium text-blue-800" to={"/reports?conversation="+encodeURIComponent(selected)+(detail.conversation.job_id?"&job="+encodeURIComponent(detail.conversation.job_id):"")}>Create report from these texts</Link>
    <ConversationContacts conversationKey={selected} onChooseJob={j=>{setJobs(previous=>[j,...previous.filter(x=>x.id!==j.id)]);setJob(j.id);setLinking(true)}}/>
    {linking&&<div className="my-4 rounded-xl border bg-slate-50 p-3"><label className="block text-sm">Find an existing job<input className={control+' mt-2 w-full'} value={jobSearch} onChange={e=>setJobSearch(e.target.value)} placeholder="Job name"/></label><button disabled={busy} className={control+' mt-2'} onClick={findJobs}>Search jobs</button><label className="mt-3 block text-sm">Linked job<select className={control+' mt-2 w-full'} value={job} onChange={e=>setJob(e.target.value)}><option value="">No job linked</option>{detail.conversation.job_id&&!jobs.some(j=>j.id===detail.conversation.job_id)&&<option value={detail.conversation.job_id}>{detail.conversation.job_name}</option>}{jobs.map(j=><option key={j.id} value={j.id}>{j.name}{j.address?' · '+j.address:''}</option>)}</select></label><button disabled={busy} onClick={saveJob} className="mt-3 min-h-11 rounded-lg bg-blue-700 px-4 text-sm text-white">Save job link</button><p className="mt-2 text-xs text-slate-500">New messages in this conversation keep this link. Message contents remain private.</p></div>}
    <div className="my-4 flex flex-wrap gap-2">{detail.has_more&&<button className={control} onClick={()=>setMessageSkip(n=>n+100)}>Older messages</button>}{messageSkip>0&&<button className={control} onClick={()=>setMessageSkip(n=>Math.max(0,n-100))}>Newer messages</button>}</div>
    <ol className="space-y-4">{[...detail.messages].reverse().map(m=><li key={m.id} className={'flex '+(m.direction==='outgoing'?'justify-end':'justify-start')}><article className={'min-w-0 max-w-[94%] rounded-2xl p-3 sm:max-w-[85%] '+(m.direction==='outgoing'?'bg-blue-50':'bg-slate-100')}><p className="mb-1 break-words text-[11px] font-medium text-slate-500">{m.direction==='outgoing'?'You':m.sender||detail.conversation.title}</p><p className="whitespace-pre-wrap break-words text-sm leading-relaxed [overflow-wrap:anywhere]">{m.retracted_at?'Message was unsent':m.text||'Attachment'}</p>{!m.retracted_at&&m.attachments?.map(a=><div key={a.guid} className="mt-3 rounded-lg border border-slate-200 bg-white/80 p-3">{a.status==='ready'?<button disabled={busy} className="flex min-h-10 items-center gap-2 break-all text-left text-sm text-blue-700" onClick={()=>openAttachment(m,a)}><Paperclip className="h-4 w-4 shrink-0"/>{a.name||'Open attachment'}</button>:<><p className="break-all text-sm">{a.name||'Attachment'}</p><p className="mt-1 text-xs text-slate-500">{attachmentLabel[a.status]||'Waiting for attachment'}</p></>}</div>)}<time className="mt-2 block text-[10px] text-slate-400">{when(m.sent_at)}{m.edited_at?' · Edited':''}</time></article></li>)}</ol><p className="mt-6 border-t pt-3 text-xs text-slate-500">Review inbox · Replies are sent from Apple Messages. Security-code messages are skipped by the Mac bridge.</p>
   </>}</section>
  </div>
  </>}
 </div>;
}