import {useEffect,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {base44} from '@/api/base44Client';
import {isAgentCenterOwner} from '@/lib/agentCenterAccess';
import {buildReportPdf,buildEmailDraft,downloadFile,fetchReportFile} from '@/components/reports/reportExport';
import {Archive,Camera,FileText,RefreshCw,Download} from 'lucide-react';

const call=async data=>(await base44.functions.invoke('field-library',data)).data;
const button='min-h-11 rounded-xl border border-slate-300 bg-white px-4 text-sm disabled:opacity-50';
const primary='min-h-11 rounded-xl bg-[#245889] px-4 text-sm font-medium text-white disabled:opacity-50';
const field='mt-2 min-h-11 w-full rounded-xl border border-slate-300 px-3 text-sm';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Denver',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const when=s=>s&&Number.isFinite(new Date(s).getTime())?new Date(s).toLocaleString('en-US',{timeZone:'America/Denver',dateStyle:'medium',timeStyle:'short'}):'Date not recorded';
function Attachment({file,onError}){
 const [source,setSource]=useState(null),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(source?.url?.startsWith('blob:'))URL.revokeObjectURL(source.url);},[source]);
 const open=async()=>{setBusy(true);try{const result=await call({action:'file',source_key:file.source_key});if(result.chunks?.length)result.url=URL.createObjectURL(await fetchReportFile(result));setSource(result);}catch(e){onError(e.response?.data?.error||'This attachment could not be opened.');}finally{setBusy(false);}};
 return <div className="min-w-0 overflow-hidden rounded-xl border bg-slate-50">{source?<a className="block break-all text-sm text-blue-800" href={source.url} target="_blank" rel="noreferrer">{source.mime_type?.startsWith('image/')?<img className="h-40 w-full object-contain" src={source.url} alt={file.name}/>:<span className="block p-4">Open {file.name}</span>}</a>:<button className="flex min-h-28 w-full flex-col items-center justify-center gap-2 p-3 text-sm text-blue-800" disabled={busy} onClick={open}>{file.type==='photo'?<Camera className="h-5 w-5"/>:<FileText className="h-5 w-5"/>}{busy?'Opening…':file.type==='photo'?'View photo':file.name}</button>}</div>;
}
export default function ReportLibrary(){
 const [params,setParams]=useSearchParams(),[owner,setOwner]=useState(null),[run,setRun]=useState(null),[query,setQuery]=useState(''),[includeDeleted,setIncludeDeleted]=useState(false);
 const [projects,setProjects]=useState([]),[moreProjects,setMoreProjects]=useState(false),[project,setProject]=useState(null),[reports,setReports]=useState([]),[moreReports,setMoreReports]=useState(false),[selected,setSelected]=useState(new Set());
 const [busy,setBusy]=useState(''),[error,setError]=useState(''),[title,setTitle]=useState(''),[reportDate,setReportDate]=useState(today),[notes,setNotes]=useState(''),[recipient,setRecipient]=useState(''),[pdf,setPdf]=useState(null),[contacts,setContacts]=useState([]);
 const task=async(label,fn)=>{setBusy(label);setError('');try{await fn();}catch(e){setError(e.response?.data?.error||e.message||'Please retry.');}finally{setBusy('');}};
 const status=async()=>setRun((await call({action:'status'})).run);
 const loadProjects=async(append=false)=>{const r=await call({action:'projects',search:query,include_deleted:includeDeleted,offset:append?projects.length:0});setProjects(append?[...projects,...r.projects]:r.projects);setMoreProjects(r.has_more);};
 const openProject=async(id,append=false)=>task('Opening saved reports…',async()=>{const r=await call({action:'project',project_id:id,include_deleted:includeDeleted,offset:append?reports.length:0});setProject(r.project);setReports(append?[...reports,...r.reports]:r.reports);setMoreReports(r.has_more);if(!append){setSelected(new Set());setTitle(r.project.name+' — Field report');setReportDate(r.reports[0]?.date||today());setNotes('');setRecipient('');setPdf(null);setParams({project:id});}});
 useEffect(()=>{base44.auth.me().then(u=>setOwner(isAgentCenterOwner(u))).catch(()=>setOwner(false));},[]);
 useEffect(()=>{if(!owner)return;status().catch(()=>{});const timer=setInterval(()=>status().catch(()=>{}),30000);if(params.get('project'))openProject(params.get('project'));return()=>clearInterval(timer);},[owner]);
 useEffect(()=>{if(!owner)return;let cancelled=false;const timer=setTimeout(()=>{call({action:'projects',search:query,include_deleted:includeDeleted}).then(r=>{if(!cancelled){setProjects(r.projects);setMoreProjects(r.has_more);}}).catch(e=>{if(!cancelled)setError(e.response?.data?.error||'Projects could not be loaded.');});},250);return()=>{cancelled=true;clearTimeout(timer);};},[owner,query,includeDeleted]);
 const draft={title,report_date:reportDate,notes,recipient,job_id:project?.job_id,job_name:project?.job_name,source_checked_at:project?.source_checked_at,posts:reports.filter(r=>selected.has(r.id)),messages:[]};
 const prepare=()=>task('Preparing your photo report…',async()=>setPdf(await buildReportPdf(draft,payload=>call({action:'file',source_key:payload.source_key}),setBusy)));
 if(owner===null)return <p className="p-8">Opening the report library…</p>;
 if(!owner)return <p className="p-8">The report library is private to Gabriel’s owner accounts.</p>;
 return <div className="mx-auto max-w-7xl space-y-5 p-4 pb-32 sm:p-6">
  <header className="rounded-2xl bg-[#172438] p-5 text-white sm:p-6"><p className="text-xs uppercase tracking-[.18em] text-slate-300">Glass Forge Hub</p><div className="mt-2 flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-semibold">Report library</h1><p className="mt-2 max-w-2xl text-sm text-slate-300">Your saved project history, notes, photos and documents. These copies stay in Glass Forge.</p></div><button className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-500 px-4 text-sm" disabled={!!busy} onClick={()=>task('Refreshing library…',async()=>{await status();await loadProjects();})}><RefreshCw className="h-4 w-4"/>Refresh</button></div><div className="mt-5 grid grid-cols-3 gap-3 border-t border-slate-600 pt-4">{[['Projects',run?.projects_checked||0],['Reports',run?.reports_imported||0],['Files saved',run?.files_verified||0]].map(([label,value])=><div key={label}><strong className="block text-xl">{Number(value).toLocaleString()}</strong><span className="text-xs text-slate-300">{label}</span></div>)}</div></header>
  {run&&<div role="status" className={'rounded-xl border p-4 text-sm '+(run.files_complete?'border-emerald-200 bg-emerald-50 text-emerald-900':'border-blue-200 bg-blue-50 text-blue-900')}><strong>{run.files_complete?'Import verified':run.phase==='metadata'?'Importing report history':'Saving original attachments'}</strong><p className="mt-1">{run.files_complete?'The source reports and every discovered attachment have been copied and checked.':`${Number(run.files_verified||0).toLocaleString()} of ${Number(run.files_discovered||0).toLocaleString()} files verified. You can browse reports while the transfer continues.`}</p>{run.audit?.failed_files>0&&<p className="mt-1">{run.audit.failed_files} files need another transfer attempt.</p>}</div>}
  <div className="flex flex-wrap gap-2"><Link className={button+' inline-flex items-center'} to="/reports">Prepare a live ProBuild report</Link><Link className={button+' inline-flex items-center'} to="/messages">Messages</Link><Link className={button+' inline-flex items-center'} to="/contacts">Contacts</Link></div>
  {busy&&<p role="status" className="rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{busy}</p>}{error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
  <div className="grid min-w-0 items-start gap-5 xl:grid-cols-[300px_minmax(0,1fr)]"><aside className="min-w-0 space-y-3 rounded-2xl border bg-white p-4"><label className="block text-sm font-medium">Find a project<input className={field} placeholder="Builder, lot or project" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="flex min-h-11 items-center gap-2 text-xs"><input type="checkbox" checked={includeDeleted} onChange={e=>setIncludeDeleted(e.target.checked)}/>Show projects removed in ProBuild</label><div className="max-h-80 space-y-2 overflow-y-auto xl:max-h-[65vh]">{projects.map(p=><button key={p.id} disabled={!!busy} className={'block w-full rounded-xl border p-3 text-left text-sm '+(project?.id===p.id?'border-blue-300 bg-blue-50':'hover:bg-slate-50')} onClick={()=>openProject(p.id)}><strong className="break-words">{p.name}</strong><span className="mt-1 block text-xs text-slate-500">{p.report_count} reports · {p.attachment_count} attachments{p.archived?' · Archived':''}{p.source_deleted?' · Removed in source':''}</span></button>)}{!projects.length&&<p className="p-3 text-sm text-slate-500">No matching projects in the library yet.</p>}</div>{moreProjects&&<button className={button+' w-full'} disabled={!!busy} onClick={()=>task('Loading projects…',()=>loadProjects(true))}>More projects</button>}</aside>
   <section className="min-w-0 space-y-4" aria-label="Saved project reports">{!project?<div className="rounded-2xl border bg-white p-8 text-center text-slate-500"><Archive className="mx-auto mb-3 h-9 w-9"/><h2 className="text-lg font-medium text-slate-800">Choose a project</h2><p className="mt-2 text-sm">Open its saved reports and original attachments here.</p></div>:<><div className="rounded-2xl border bg-white p-5"><h2 className="break-words text-xl font-semibold">{project.name}</h2>{project.description&&<p className="mt-3 whitespace-pre-wrap break-words text-sm">{project.description}</p>}<p className="mt-3 text-xs text-slate-500">{project.report_count} reports · Copied {when(project.source_checked_at)}</p>{project.job_id&&<Link className="mt-3 inline-block text-sm text-blue-800 underline" to={'/jobs/'+project.job_id}>{project.job_name||'Open linked job'}</Link>}</div>
    <div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Saved updates</h3><button className={button} disabled={!!busy} onClick={()=>{setSelected(selected.size===reports.length?new Set():new Set(reports.map(r=>r.id)));setPdf(null);}}>{selected.size===reports.length?'Clear selection':'Select displayed updates'}</button></div>
    {reports.map(r=><article key={r.id} className="min-w-0 rounded-2xl border bg-white p-4"><label className="flex min-h-11 gap-3"><input className="mt-1 h-5 w-5 shrink-0" type="checkbox" checked={selected.has(r.id)} onChange={e=>{setSelected(v=>{const s=new Set(v);e.target.checked?s.add(r.id):s.delete(r.id);return s;});setPdf(null);}}/><span><strong className="text-sm">{when(r.created_at)}</strong><span className="mt-1 block text-xs text-slate-500">{r.attachments.length} attachments{r.deleted?' · Removed in source':''}</span></span></label><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-relaxed">{r.message||'Photo update — no written notes in source.'}</p>{r.attachments.length>0&&<div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{r.attachments.map(a=><Attachment key={a.source_key} file={a} onError={setError}/>)}</div>}</article>)}{moreReports&&<button className={button+' w-full'} disabled={!!busy} onClick={()=>openProject(project.id,true)}>Load older reports</button>}
    <div className="space-y-4 rounded-2xl border bg-white p-5"><h3 className="text-lg font-semibold">Share a photo report</h3><p className="text-sm text-slate-500">{selected.size} saved updates selected</p><label className="block text-sm font-medium">Report title<input className={field} value={title} onChange={e=>{setTitle(e.target.value);setPdf(null);}}/></label><label className="block text-sm font-medium">Report date<input type="date" className={field+' max-w-xs'} value={reportDate} onChange={e=>{setReportDate(e.target.value);setPdf(null);}}/></label><label className="block text-sm font-medium">Your notes<textarea className={field+' min-h-28 py-3'} value={notes} onChange={e=>{setNotes(e.target.value);setPdf(null);}}/></label><label className="block text-sm font-medium">Recipient email<input type="email" list="library-contacts" className={field} value={recipient} onChange={e=>setRecipient(e.target.value)}/></label><datalist id="library-contacts">{contacts.filter(c=>c.email).map(c=><option key={c.key} value={c.email}>{c.name} · {c.builder_label||c.builder||''}</option>)}</datalist><button className="min-h-10 text-sm text-blue-800 underline" disabled={!!busy} onClick={()=>task('Loading contacts…',async()=>setContacts((await base44.functions.invoke('contacts-directory',{action:'directory'})).data.contacts||[]))}>Use spreadsheet contacts</button><div><button className={primary} disabled={!!busy||!selected.size||!title.trim()} onClick={prepare}>Prepare PDF with saved photos</button></div>{pdf&&<div className="space-y-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="break-words text-sm text-emerald-900">Ready · {(pdf.size/1048576).toFixed(1)} MB · {pdf.name}</p><div className="flex flex-wrap gap-2"><button className={button+' flex items-center gap-2'} onClick={()=>downloadFile(pdf)}><Download className="h-4 w-4"/>Download PDF</button>{navigator.canShare?.({files:[pdf]})&&<button className={primary} onClick={()=>task('Opening share options…',async()=>{try{await navigator.share({files:[pdf],title});}catch(e){if(e.name!=='AbortError')throw e;}})}>Share PDF</button>}<button className={button} onClick={()=>task('Preparing email draft…',async()=>downloadFile(await buildEmailDraft(draft,pdf)))}>Download email draft</button></div></div>}</div>
   </>}</section></div>
 </div>;
}
